/**
 * @file lib/digests.ts
 * @description Firestore CRUD service for daily digests.
 *
 * Digests aggregate 24h of agent activity into a summary for the
 * notification bell. Generated by the daily-digest Inngest cron job.
 *
 * @phase Impulse v1.0 — Phase 4: Intelligence Layer
 */

import { db } from '@/lib/firebase-admin';
import { createLogger } from '@/lib/logger';

const log = createLogger('digests');

// ============================================================================
// TYPES
// ============================================================================

export interface DigestSummary {
  signalsDiscovered: number;
  connectionsFound: number;
  entitiesEnriched: number;
  insightsGenerated: number;
  tokenUsage: number;
  tokenBudget: number;
}

export interface DigestHighlight {
  type: 'discovery' | 'connection' | 'pattern';
  title: string;
  entityId?: string;
}

export interface Digest {
  id: string;
  userId: string;
  date: string;
  summary: DigestSummary;
  highlights: DigestHighlight[];
  createdAt: number;
  read: boolean;
}

// ============================================================================
// CRUD
// ============================================================================

/**
 * A digest carries no signal when every activity counter is zero. These are
 * either a quiet 24h window (nothing to report) or — pre-fix — noise from
 * the daily cron unconditionally creating one digest per active user
 * regardless of activity. Shared by the writer (skip creating one) and the
 * reader (hide any that already made it into Firestore, no migration).
 */
export function isZeroActivityDigest(
  summary: Pick<DigestSummary, 'signalsDiscovered' | 'connectionsFound' | 'insightsGenerated'>
): boolean {
  return summary.signalsDiscovered + summary.connectionsFound + summary.insightsGenerated === 0;
}

// Read window wide enough to skip past any pre-fix backlog of zero-activity
// digests without a migration; the per-user collection is small so this
// stays well inside the Firestore read budget.
const UNREAD_DIGEST_SCAN_LIMIT = 200;
const UNREAD_DIGEST_DISPLAY_LIMIT = 10;

export async function createDigest(data: Omit<Digest, 'id' | 'createdAt' | 'read'>): Promise<void> {
  const id = `digest-${data.userId}-${data.date}`;
  await db
    .collection('digests')
    .doc(id)
    .set({ ...data, id, createdAt: Date.now(), read: false });
  log.info('Digest created', { id, userId: data.userId });
}

export async function getUnreadDigests(userId: string): Promise<Digest[]> {
  const snap = await db
    .collection('digests')
    .where('userId', '==', userId)
    .where('read', '==', false)
    .limit(UNREAD_DIGEST_SCAN_LIMIT)
    .get();
  return snap.docs
    .map((d) => d.data() as Digest)
    .filter((digest) => !isZeroActivityDigest(digest.summary))
    .slice(0, UNREAD_DIGEST_DISPLAY_LIMIT);
}

export async function markDigestRead(digestId: string): Promise<void> {
  await db.collection('digests').doc(digestId).update({ read: true });
}

/** Marks every unread digest for a user as read, chunked at Firestore's 500-write batch cap. Returns the count updated. */
export async function markAllDigestsRead(userId: string): Promise<number> {
  const snap = await db.collection('digests').where('userId', '==', userId).where('read', '==', false).get();
  if (snap.empty) return 0;

  const docs = snap.docs;
  for (let i = 0; i < docs.length; i += 500) {
    const batch = db.batch();
    for (const doc of docs.slice(i, i + 500)) {
      batch.update(doc.ref, { read: true });
    }
    await batch.commit();
  }
  log.info('All digests marked read', { userId, count: docs.length });
  return docs.length;
}
