/**
 * @file lib/reports.ts
 * @description Data access layer for Reports
 *
 * Reports are self-contained HTML+CSS documents generated by agents
 * (Creator, Strategist) or created by users. They are stored in the
 * Firestore `reports` collection and served publicly via /share/report/[id].
 *
 * NOTE: Reports do NOT use entity-factory because they don't need
 * slug generation, Neo4j sync, or other entity lifecycle features.
 * They use direct Firestore operations instead.
 *
 * @author Radarist Team
 * @created 2026-02-23
 */

// Server-side reads/writes use the **admin** SDK so Firestore rules can't
// silently filter the result to empty. The client SDK invoked from a
// Next.js API route has no signed-in user context; any deployed rule that
// requires `request.auth != null` would reject the read, returning [] and
// surfacing as an empty /reports listing in the UI.
import { db } from '@/lib/firebase-admin';
import { withDeadline } from '@/lib/firestore-deadline';
import { createReportSchema, updateReportSchema } from '@/lib/schemas/report';
import type { CreateReportInput, UpdateReportInput, Report } from '@/lib/schemas/report';
import { createLogger } from '@/lib/logger';
import { decodeHtmlEntities } from '@/lib/decode-html-entities';
import { assertPublishableReportHtml } from '@/lib/reports/publication-policy';
import { assertReportReferenceIntegrity } from '@/lib/reports/reference-integrity';
import { stageVersionCapture, type StagedVersionWrite } from '@/lib/reports/report-versions';

const log = createLogger('reports');

/** Firestore collection name for reports */
const COLLECTION_NAME = 'reports';

/** Normalize Firestore Timestamp fields to ISO strings */
function normalizeTimestamps(data: Record<string, unknown>): Record<string, unknown> {
  for (const key of ['createdAt', 'updatedAt']) {
    const val = data[key];
    if (val && typeof val !== 'string' && typeof (val as { toDate?: unknown }).toDate === 'function') {
      data[key] = (val as { toDate: () => Date }).toDate().toISOString();
    }
  }
  return data;
}

/**
 * Normalize a raw Firestore report doc for consumption: Timestamp → ISO
 * strings, plus a single read-boundary entity decode on `title`.
 *
 * The decode heals reports stored before the writer-side decode shipped
 * (agent publishReport calls sent titles already HTML-entity-encoded, e.g.
 * "MCP &amp; ..."). Decoding ONCE here — instead of per-consumer — means the
 * table, detail header, share page (tab title / OG / JSON-LD / h1), agent
 * log, client-side search + sort, and the download filename/escapeHtml all
 * see the same decoded plain-text value; a consumer-side decode on top of
 * this one would double-decode (stored "&amp;amp;" → "&"), so consumers MUST
 * render `title` verbatim. `metadata.description` is left untouched — an
 * audit of every stored publishReport call (logs/agent.log) found the
 * corruption class in titles only.
 */
function normalizeReportDoc(data: Record<string, unknown>): Record<string, unknown> {
  normalizeTimestamps(data);
  if (typeof data.title === 'string') {
    data.title = decodeHtmlEntities(data.title);
  }
  return data;
}

const reportsCol = () => db.collection(COLLECTION_NAME);

// REPORT-001/REPORT-002 lifecycle helpers are pure and client-safe; they live
// in the schema module (the UI imports them from there) and are re-exported
// here so server callers keep one import surface.
import { isPublishedReport, reportLifecycleState } from '@/lib/schemas/report';
export { isPublishedReport, reportLifecycleState };
export type { ReportLifecycleState } from '@/lib/schemas/report';

/**
 * SEC-009 — the single ownership predicate every authenticated report surface
 * resolves through. True only when the stored document carries an `ownerId`
 * equal to the caller's. Ownerless legacy records are DENIED for everyone
 * until an explicit guarded migration assigns them, so a pre-ownership doc
 * can never leak cross-user.
 */
function isOwnedBy(data: { ownerId?: unknown } | null | undefined, ownerId: string): boolean {
  return Boolean(ownerId) && data?.ownerId === ownerId;
}

/** REPORT-001: the design-review fields to persist, only when defined (Firestore rejects undefined). */
function reviewLifecycleFields(input: {
  reviewStatus?: 'published' | 'needs-review';
  designPassVerdict?: 'PASS' | 'FAIL' | 'UNREVIEWED';
  designPassDetails?: string;
}): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  if (input.reviewStatus !== undefined) out.reviewStatus = input.reviewStatus;
  if (input.designPassVerdict !== undefined) out.designPassVerdict = input.designPassVerdict;
  if (input.designPassDetails !== undefined) out.designPassDetails = input.designPassDetails;
  return out;
}

export interface ReportArtifactIdentity {
  sha256: string;
  cssSha256: string;
  bytes: number;
  stagedAt: string;
  revisionNumber: number;
  reviewedBy: readonly ['design-pass', 'critique-report'];
  evidenceBundleSha256: string;
}

/**
 * Generate a unique report ID.
 * Uses a combination of timestamp and random string for uniqueness.
 */
function generateReportId(): string {
  const timestamp = Date.now().toString(36);
  const random = Math.random().toString(36).substring(2, 10);
  return `report-${timestamp}-${random}`;
}

/**
 * Create a new report in Firestore.
 *
 * Validates input with Zod, generates a unique ID, adds creation timestamp,
 * and stores the document in the `reports` collection.
 *
 * @param data - Report creation input (validated against createReportSchema)
 * @returns The created Report with id and createdAt fields
 * @throws ZodError if input validation fails
 * @throws Error if Firestore write fails
 *
 * @example
 * ```typescript
 * const report = await createReport({
 *   title: 'Q1 Radar Overview',
 *   html: '<html>...</html>',
 *   createdBy: 'agent',
 *   agentType: 'creator',
 *   entityIds: ['tech-1'],
 *   metadata: {
 *     description: 'Quarterly overview',
 *     dataSnapshotAt: new Date().toISOString(),
 *   },
 * });
 * ```
 */
export async function createReport(data: CreateReportInput): Promise<Report> {
  // Validate input
  const validated = createReportSchema.parse(data);

  // UX-021: reject executable/off-origin report HTML at publication with an
  // actionable static-conversion error, before it can be stored and then render
  // blank in the scriptless viewer.
  assertPublishableReportHtml(validated.html);
  assertReportReferenceIntegrity(validated.html);

  const id = generateReportId();
  const createdAt = new Date().toISOString();

  const report: Report = {
    id,
    title: validated.title,
    html: validated.html,
    createdAt,
    createdBy: validated.createdBy,
    ownerId: validated.ownerId,
    agentType: validated.agentType,
    missionId: validated.missionId,
    entityIds: validated.entityIds,
    metadata: validated.metadata,
    shared: validated.shared,
  };

  // Firestore rejects undefined values — strip optional fields that are undefined
  const firestoreData = Object.fromEntries(Object.entries(report).filter(([, v]) => v !== undefined));

  try {
    await withDeadline(reportsCol().doc(id).set(firestoreData), 'createReport.set');
    log.info('Report created', { id, title: report.title, createdBy: report.createdBy });
    return report;
  } catch (error) {
    log.error('Failed to create report', error instanceof Error ? error : new Error(String(error)));
    throw error;
  }
}

export interface UpsertReportBySlotInput {
  missionId: string;
  slotName: string;
  title: string;
  html: string;
  description: string;
  /** Actor type that produced the report: 'agent' = mission orchestrator, 'user' = direct chat tool. */
  createdBy: 'agent' | 'user';
  /**
   * Owning user UID. Required for per-user authorization in listReports /
   * getReportById / update / restore / delete. For mission-driven publishes
   * this is the mission's dispatcher (mission.userId), not the orchestrator's
   * service identity. Pre-2026-05-05 reports may lack this field — those are
   * historical orphans, addressed by a separate backfill (Phase 6).
   */
  ownerId: string;
  agentType?: string;
  entityIds: string[];
  /**
   * REPORT-001 design-review lifecycle. When the publisher ran a design review,
   * it passes the resulting status/verdict so the persisted artifact is honest
   * about whether it is a final `published` report or a withheld `needs-review`
   * draft. Omitted when no design review ran (→ the doc keeps/defaults to
   * `published`).
   */
  reviewStatus?: 'published' | 'needs-review';
  designPassVerdict?: 'PASS' | 'FAIL' | 'UNREVIEWED';
  designPassDetails?: string;
  /** Exact self-contained export bytes and the post-staging reviews bound to them. */
  artifactIdentity?: ReportArtifactIdentity;
  /**
   * DISC-014: actor whose save produced this revision, stamped onto the captured
   * version (e.g. `agent:creator`). Omitted → the version is attributed `unknown`.
   */
  savedBy?: string;
}

export interface UpsertReportBySlotResult {
  reportId: string;
  /**
   * REPORT-002: the authenticated private route (`/reports/{id}`). A mission
   * publish is born `shared:false`, so no public /share link exists yet —
   * returning one here taught agents to hand out URLs that render
   * "Report Not Shared". Sharing is a separate explicit approval.
   */
  reportUrl: string;
  isUpsert: boolean;
}

/**
 * Upsert a report keyed on (missionId, slotName).
 *
 * - If a report with this composite key exists: update its html/title/description/updatedAt in place.
 * - If not: insert a new report.
 *
 * The composite key keeps `/share/report/<id>` URLs stable across mission revision turns.
 *
 * Concurrency: the query→if-empty→setDoc sequence is NOT atomic. This is safe
 * only because publishes are serialized per (missionId, slotName) by the
 * orchestrator + MCP single-flight processing. If a future caller invokes this
 * helper from a parallel context, switch to deterministic doc IDs
 * (`${missionId}__${slotName}`) with `setDoc(..., { merge: true })` to remove
 * the race entirely.
 */
export async function upsertReportBySlot(input: UpsertReportBySlotInput): Promise<UpsertReportBySlotResult> {
  // UX-021: gate both the insert and update paths — a mission publish must not
  // store executable HTML that would render blank in the static viewer.
  assertPublishableReportHtml(input.html);
  assertReportReferenceIntegrity(input.html);

  const existingQuery = reportsCol().where('missionId', '==', input.missionId).where('slotName', '==', input.slotName);
  const snapshot = await withDeadline(existingQuery.get(), 'upsertReportBySlot.get');

  const now = new Date().toISOString();
  // publishReport (the AI tool) doesn't go through createReportSchema, so this
  // is the write-time decode for the path that actually produced the
  // corrupted-title bug: an agent's `title` arg arriving HTML-entity-encoded
  // (e.g. copied verbatim out of its own <title> tag) gets stored literally
  // as "&amp;" and would otherwise render that way forever — see
  // decode-html-entities.ts and ReportsTable.tsx's matching display-time fix
  // for titles stored before this change shipped.
  const title = decodeHtmlEntities(input.title);

  if (!snapshot.empty) {
    // Update existing
    const existingDoc = snapshot.docs[0];
    const docRef = existingDoc.ref;
    const reportId = existingDoc.id;
    // DISC-014: capture the outgoing html into version history and swap the head
    // inside one transaction, so a revision can never land a new head without
    // its history version (or vice versa). Only when the html actually changes:
    // an idempotent same-html republish must not consume history or the one-step
    // buffer with a no-op self-copy (same guard as updateReport).
    await withDeadline(
      db.runTransaction(async (tx) => {
        const fresh = await tx.get(docRef);
        // The slot was located outside the transaction; if it was deleted in the
        // narrow window since, fail rather than silently resurrect it.
        if (!fresh.exists) throw new Error('Report not found');
        const existing = fresh.data() as { html?: string; previousHtml?: string; ownerId?: string };
        // SEC-009 defense-in-depth at the WRITE chokepoint. The slot is located
        // by (missionId, slotName) alone, so without this a forged missionId
        // could overwrite another user's artifact even though every read path
        // denies it. An ownerless legacy doc republished by its OWN mission is
        // healed instead (the mission's dispatcher is authoritative — the same
        // derivation the guarded migration applies), so it stops being invisible.
        if (existing.ownerId && input.ownerId && existing.ownerId !== input.ownerId) {
          throw new Error('Report not found');
        }
        const outgoingHtml = existing.html;
        const htmlChanged = Boolean(outgoingHtml) && outgoingHtml !== input.html;

        let versionWrites: StagedVersionWrite[] = [];
        if (htmlChanged) {
          versionWrites = await stageVersionCapture(tx, docRef, existing, {
            savedBy: input.savedBy,
            reason: 'revision',
          });
        }

        // Dotted-path update preserves other metadata fields (e.g. dataSnapshotAt
        // set at insert time). Don't simplify to `metadata: { description: ... }`
        // — that would overwrite the entire metadata map.
        tx.update(docRef, {
          title,
          html: input.html,
          updatedAt: now,
          'metadata.description': input.description,
          entityIds: input.entityIds,
          ...(!existing.ownerId && input.ownerId ? { ownerId: input.ownerId } : {}),
          ...(htmlChanged ? { previousHtml: outgoingHtml } : {}),
          // REPORT-001: a re-publish re-runs the design review, so the freshly
          // computed status/verdict replace the prior ones for this same slot.
          ...reviewLifecycleFields(input),
          // Always replace or clear this identity on publish. A later legacy
          // rewrite must never inherit proof for bytes it did not review.
          artifactIdentity: input.artifactIdentity ?? null,
        });
        for (const write of versionWrites) tx.set(write.ref, write.data);
      }),
      'upsertReportBySlot.updateTransaction'
    );
    log.info('Report upserted (update path)', { reportId, missionId: input.missionId, slotName: input.slotName });
    return { reportId, reportUrl: `/reports/${reportId}`, isUpsert: true };
  }

  // Insert new
  const id = generateReportId();
  const data = {
    id,
    title,
    html: input.html,
    createdAt: now,
    createdBy: input.createdBy,
    ownerId: input.ownerId,
    agentType: input.agentType,
    missionId: input.missionId,
    slotName: input.slotName,
    entityIds: input.entityIds,
    metadata: { description: input.description, dataSnapshotAt: now },
    shared: false,
    // EU AI Act Art 50(2)/(4): every report is AI-generated/assisted; mark it so the
    // share page can surface the machine-readable + visible AI disclosure.
    aiGenerated: true,
    // REPORT-001: stamp the design-review lifecycle so a design-failing draft is
    // born `needs-review` (off catalog/share) rather than a final published doc.
    ...reviewLifecycleFields(input),
    ...(input.artifactIdentity ? { artifactIdentity: input.artifactIdentity } : {}),
  };
  const firestoreData = Object.fromEntries(Object.entries(data).filter(([, v]) => v !== undefined));
  await withDeadline(reportsCol().doc(id).set(firestoreData), 'upsertReportBySlot.set');
  log.info('Report upserted (insert path)', { reportId: id, missionId: input.missionId, slotName: input.slotName });
  return { reportId: id, reportUrl: `/reports/${id}`, isUpsert: false };
}

/**
 * Get a report by its ID.
 *
 * @param id - The report ID to look up
 * @returns The Report if found, or null if not found
 * @throws Error if Firestore read fails
 *
 * @example
 * ```typescript
 * const report = await getReportById('report-abc123');
 * if (report) {
 *   console.log(report.title);
 * }
 * ```
 */
export async function getReportById(id: string): Promise<Report | null> {
  try {
    const snapshot = await withDeadline(reportsCol().doc(id).get(), 'getReportById.get');
    if (!snapshot.exists) return null;
    return normalizeReportDoc(snapshot.data() as Record<string, unknown>) as Report;
  } catch (error) {
    log.error('Failed to get report', error instanceof Error ? error : new Error(String(error)));
    throw error;
  }
}

/**
 * SEC-009 — exact-ID read for the authenticated surface. Returns null for
 * absent, foreign, AND ownerless reports (one indistinguishable not-found),
 * so IDs cannot be used as an existence oracle across users. Internal/system
 * callers that legitimately need unscoped access (the public share page's
 * shared-state gate, the mission engine reading its own publishes) stay on
 * `getReportById`.
 */
export async function getReportOwnedBy(id: string, ownerId: string): Promise<Report | null> {
  try {
    const snapshot = await withDeadline(reportsCol().doc(id).get(), 'getReportOwnedBy.get');
    if (!snapshot.exists) return null;
    const data = snapshot.data() as Record<string, unknown>;
    if (!isOwnedBy(data, ownerId)) return null;
    return normalizeReportDoc(data) as Report;
  } catch (error) {
    log.error('Failed to get owned report', error instanceof Error ? error : new Error(String(error)), { id });
    throw error;
  }
}

/**
 * All reports for a mission, newest-first (createdAt desc). Includes the full
 * html body of each — the revision regression-restore path (MISSION-002) needs
 * every slot's original body so it can restore each report the revision may
 * have clobbered, not just the newest one (a mission can publish up to
 * MAX_SLOTS distinct deliverables). Best-effort: returns [] on no match or
 * query failure (never throws). Single equality filter + in-memory sort → no
 * composite index required.
 */
export async function getReportsByMissionId(missionId: string): Promise<Report[]> {
  try {
    const snapshot = await withDeadline(
      reportsCol().where('missionId', '==', missionId).get(),
      'getReportsByMissionId.get'
    );
    if (snapshot.empty) return [];
    const reports = snapshot.docs.map(
      (docSnap) => normalizeReportDoc(docSnap.data() as Record<string, unknown>) as Report
    );
    reports.sort((a, b) => String(b.createdAt ?? '').localeCompare(String(a.createdAt ?? '')));
    return reports;
  } catch (error) {
    log.error('Failed to get reports by missionId', error instanceof Error ? error : new Error(String(error)), {
      missionId,
    });
    return [];
  }
}

/**
 * Get the most-recently-created report for a mission, if any. Used to salvage a
 * published report when a mission ends without a clean result — e.g. the agent
 * published the report, then overran its budget and the SDK returned a failure
 * with an empty result. Best-effort: returns null on no match or query failure
 * (never throws), so callers can use it on a recovery path without guarding.
 */
export async function getLatestReportByMissionId(missionId: string): Promise<Report | null> {
  const reports = await getReportsByMissionId(missionId);
  return reports[0] ?? null;
}

/**
 * SEC-009 / REPORT-002 — the owner-scoped counterpart of
 * `getReportsByMissionId`, for authenticated surfaces that resolve a mission's
 * deliverables on behalf of a specific user (run-detail and activity views
 * that must not surface another user's — or an ownerless legacy — report).
 *
 * Contract, and how it differs from the best-effort legacy reader:
 * - The OWNER filter is pushed into Firestore alongside the mission filter, so
 *   another user's report bodies are never downloaded (`ownerId ==` also drops
 *   ownerless legacy docs at the query layer). `isOwnedBy` is retained as an
 *   in-memory defense-in-depth check, not the primary boundary — this closes
 *   the cross-tenant read/cost-amplification hole where a caller attaches large
 *   reports to another user's `missionId`.
 * - Blank/whitespace `missionId` OR `ownerId` returns `[]` WITHOUT touching
 *   Firestore — never fall back to an unscoped mission read. Only trimmed for
 *   the emptiness check; the exact IDs are used verbatim in the query.
 * - Storage/query failures PROPAGATE. Unlike `getReportsByMissionId` (a
 *   recovery-path helper that swallows errors to `[]`), an authenticated
 *   listing must surface a read failure rather than masquerade it as
 *   "this user has no reports for this mission".
 * - Deterministic ordering: newest-first by `createdAt`, with report `id` as a
 *   stable tiebreaker so equal timestamps never reorder between reads.
 *
 * Two equality filters (no range/orderBy in the query) + in-memory sort → no
 * composite index required.
 */
export async function getReportsByMissionIdOwnedBy(missionId: string, ownerId: string): Promise<Report[]> {
  // Trim only to validate emptiness; the exact IDs are used in the query.
  if (!missionId?.trim() || !ownerId?.trim()) return [];
  try {
    const snapshot = await withDeadline(
      reportsCol().where('missionId', '==', missionId).where('ownerId', '==', ownerId).get(),
      'getReportsByMissionIdOwnedBy.get'
    );
    if (snapshot.empty) return [];
    const reports = snapshot.docs
      .map((docSnap) => docSnap.data() as Record<string, unknown>)
      // Defense-in-depth: the query already scopes to this owner; re-check in
      // memory so a mis-scoped query can never leak a foreign/ownerless doc.
      .filter((data) => isOwnedBy(data, ownerId))
      .map((data) => normalizeReportDoc(data) as Report);
    reports.sort((a, b) => {
      const byCreatedAt = String(b.createdAt ?? '').localeCompare(String(a.createdAt ?? ''));
      return byCreatedAt !== 0 ? byCreatedAt : String(a.id ?? '').localeCompare(String(b.id ?? ''));
    });
    return reports;
  } catch (error) {
    log.error('Failed to get owned reports by missionId', error instanceof Error ? error : new Error(String(error)), {
      missionId,
    });
    throw error;
  }
}

/**
 * List-payload projection of a Report: everything except the (potentially
 * megabyte-scale) html/previousHtml bodies. The list UIs (ReportsTable,
 * useReportsPage, AgentLog) render only metadata; full content is served by
 * the detail path (getReportById).
 */
export type ReportListItem = Omit<Report, 'html'>;

/**
 * List all reports, ordered by creation date (newest first).
 *
 * Returns the list projection — html and previousHtml are stripped so the
 * /api/reports listing payload stays small. Use getReportById for full
 * content (the report viewer and the download path already do).
 *
 * @returns Array of ReportListItem objects sorted by createdAt desc
 * @throws Error if Firestore query fails
 *
 * @example
 * ```typescript
 * const reports = await listReports();
 * console.log(`Found ${reports.length} reports`);
 * ```
 */
export async function listReports(): Promise<ReportListItem[]> {
  try {
    const snapshot = await withDeadline(reportsCol().orderBy('createdAt', 'desc').get(), 'listReports.get');
    return (
      snapshot.docs
        .map((docSnap) => normalizeReportDoc(docSnap.data() as Record<string, unknown>))
        // REPORT-001: the catalog lists final artifacts only — a `needs-review`
        // draft (design review did not pass) is withheld. Missing status →
        // published (back-compat with every pre-REPORT-001 report).
        .filter((data) => isPublishedReport(data.reviewStatus))
        .map((data) => toListItem(data))
    );
  } catch (error) {
    log.error('Failed to list reports', error instanceof Error ? error : new Error(String(error)));
    throw error;
  }
}

/** Strip the heavy content fields; keep everything else (missionId, slotName, shared, updatedAt, metadata, …). */
function toListItem(data: Record<string, unknown>): ReportListItem {
  const { html: _html, previousHtml: _previousHtml, ...listFields } = data;
  return listFields as ReportListItem;
}

/**
 * SEC-009 — the owner-scoped catalog listing behind GET /api/reports. Filters
 * server-side on `ownerId` (ownerless legacy docs are excluded by the query
 * itself), newest-first. Empty ownerId → [] without touching Firestore (fail
 * closed, never fall back to a global list).
 *
 * REPORT-002: unlike the global `listReports`, the OWNER's catalog INCLUDES
 * `needs-review` drafts — a paid draft must stay owner-visible with its
 * review state annotated, not vanish. Public surfaces keep excluding drafts
 * (share page fails closed; `listReports` remains final-artifacts-only for
 * internal consumers like stale-report discovery).
 */
export async function listReportsOwnedBy(ownerId: string, opts: { limit?: number } = {}): Promise<ReportListItem[]> {
  if (!ownerId) return [];
  try {
    // The chat catalog asks for a bounded slice; the /reports page asks for
    // everything. Push the bound into Firestore rather than reading the whole
    // collection and slicing in memory.
    const base = reportsCol().where('ownerId', '==', ownerId).orderBy('createdAt', 'desc');
    const snapshot = await withDeadline(
      (opts.limit !== undefined ? base.limit(opts.limit) : base).get(),
      'listReportsOwnedBy.get'
    );
    return snapshot.docs
      .map((docSnap) => normalizeReportDoc(docSnap.data() as Record<string, unknown>))
      .map((data) => toListItem(data));
  } catch (error) {
    log.error('Failed to list owned reports', error instanceof Error ? error : new Error(String(error)));
    throw error;
  }
}

/**
 * Update an existing report.
 *
 * @param id - The report ID to update
 * @param updates - Partial update fields (validated against updateReportSchema)
 * @returns The merged Report with updated fields
 * @throws ZodError if input validation fails
 * @throws Error('Report not found') if the report doesn't exist
 * @throws Error if Firestore write fails
 */
export async function updateReport(
  id: string,
  updates: UpdateReportInput,
  opts: { savedBy?: string; requireOwnerId?: string } = {}
): Promise<Report> {
  const validated = updateReportSchema.parse(updates);

  // UX-021: a report edit that replaces the HTML must clear the same gate as a
  // fresh publish. Metadata-only edits (no html) are unaffected.
  if (validated.html !== undefined) {
    assertPublishableReportHtml(validated.html);
    assertReportReferenceIntegrity(validated.html);
  }

  try {
    const reportRef = reportsCol().doc(id);
    // DISC-014: read-capture-write runs in a transaction so the version snapshot
    // and the head html swap are one atomic unit — a concurrent writer can't
    // interleave and produce a head without its history version (or vice versa).
    const result = await withDeadline(
      db.runTransaction(async (tx) => {
        const snapshot = await tx.get(reportRef);
        if (!snapshot.exists) {
          throw new Error('Report not found');
        }
        // SEC-009: ownership is checked INSIDE the transaction (no TOCTOU
        // window) and a mismatch — including an ownerless legacy doc — throws
        // the exact not-found error, so callers can't distinguish foreign
        // from absent.
        if (
          opts.requireOwnerId !== undefined &&
          !isOwnedBy(snapshot.data() as { ownerId?: unknown }, opts.requireOwnerId)
        ) {
          throw new Error('Report not found');
        }

        const existing = normalizeReportDoc(snapshot.data() as Record<string, unknown>) as Report & {
          previousHtml?: string;
        };

        // REPORT-002: public sharing is unavailable for review drafts. The
        // gate runs INSIDE the transaction on the persisted status (plus any
        // status this same update sets), so a draft can only be shared by an
        // explicit approval that flips reviewStatus to 'published' first or
        // in the same call.
        if (validated.shared === true) {
          const effectiveReviewStatus = validated.reviewStatus ?? existing.reviewStatus;
          if (!isPublishedReport(effectiveReviewStatus)) {
            throw new Error('Report is pending review and cannot be shared');
          }
        }

        const updatedAt = new Date().toISOString();
        const { metadata, ...scalars } = validated;
        const definedScalars = Object.fromEntries(Object.entries(scalars).filter(([, v]) => v !== undefined));
        const definedMetadata = Object.fromEntries(Object.entries(metadata ?? {}).filter(([, v]) => v !== undefined));

        const updatedFields: Record<string, unknown> = {
          ...definedScalars,
          // Dotted-path updates preserve metadata fields not included in this
          // update (e.g. dataSnapshotAt set at insert time, ogImage). Don't
          // simplify to `metadata: { ... }` — that would overwrite the entire
          // metadata map.
          ...Object.fromEntries(Object.entries(definedMetadata).map(([key, value]) => [`metadata.${key}`, value])),
          updatedAt,
        };

        // Capture the outgoing html into version history AND keep the one-step
        // previousHtml backup — only when the html actually CHANGES. An
        // idempotent same-value write must not consume the undo buffer or append
        // a duplicate version. The MISSION-002 regression restore writes the
        // original html back to every slot it snapshotted, including slots the
        // revision never touched — without this guard those untouched reports
        // would lose their real one-step backup to a no-op self-copy.
        let versionWrites: StagedVersionWrite[] = [];
        if (validated.html !== undefined && existing.html && validated.html !== existing.html) {
          updatedFields.previousHtml = existing.html;
          versionWrites = await stageVersionCapture(tx, reportRef, existing, {
            savedBy: opts.savedBy,
            reason: 'edit',
          });
        }

        tx.update(reportRef, updatedFields);
        for (const write of versionWrites) tx.set(write.ref, write.data);

        return {
          ...existing,
          ...definedScalars,
          metadata: { ...existing.metadata, ...definedMetadata },
          updatedAt,
        } as Report;
      }),
      'updateReport.transaction'
    );

    log.info('Report updated', { id, savedBy: opts.savedBy });
    return result;
  } catch (error) {
    if (
      error instanceof Error &&
      (error.message === 'Report not found' || error.message === 'Report is pending review and cannot be shared')
    ) {
      throw error;
    }
    log.error('Failed to update report', error instanceof Error ? error : new Error(String(error)));
    throw error;
  }
}

/**
 * Restore a report to an earlier version (DISC-014).
 *
 * - With `opts.versionId`: restore that specific point-in-time version from the
 *   history subcollection.
 * - Without it: the legacy one-step swap — restore the `previousHtml` backup
 *   (reversible: the outgoing html becomes the new backup, so restoring again
 *   swaps back). Kept for back-compat with the existing restore route + AI tool.
 *
 * EITHER WAY the restore ALSO snapshots the current head into history first, so
 * the pre-restore state is never lost — history stays monotonic and append-only.
 *
 * @param id - The report ID to restore
 * @param opts.versionId - Restore this specific historical version (optional)
 * @param opts.savedBy - Actor performing the restore, stamped on the snapshot
 * @returns The restored Report
 * @throws Error('Report not found') if the report doesn't exist
 * @throws Error('Version not found') if `opts.versionId` doesn't resolve
 * @throws Error('No previous version available') if the legacy swap has no backup
 * @throws Error if Firestore write fails
 */
export async function restoreReportVersion(
  id: string,
  opts: {
    versionId?: string;
    savedBy?: string;
    requireOwnerId?: string;
    /**
     * REPORT-004: lifecycle fields to restore ATOMICALLY with the html in the
     * same transaction (reviewStatus / design verdict / gate receipt). The
     * regression rollback uses this so a restored original never keeps the
     * rejected revision's lifecycle. `qualityGate: null` clears the receipt.
     */
    alsoSet?: {
      reviewStatus?: 'published' | 'needs-review';
      designPassVerdict?: 'PASS' | 'FAIL' | 'UNREVIEWED';
      designPassDetails?: string;
      qualityGate?: import('@/lib/schemas/report').ReportQualityGate | null;
    };
  } = {}
): Promise<Report> {
  try {
    const reportRef = reportsCol().doc(id);

    // Read-capture-write runs inside an admin-SDK transaction so a concurrent
    // writer (e.g. the AI updateReport tool landing a revision between our
    // read and write) can't interleave and corrupt the swap or drop a version.
    const restored = await withDeadline(
      db.runTransaction(async (tx) => {
        const snapshot = await tx.get(reportRef);
        if (!snapshot.exists) {
          throw new Error('Report not found');
        }
        // SEC-009: same in-transaction owner guard + indistinguishable
        // not-found as updateReport (see its note).
        if (
          opts.requireOwnerId !== undefined &&
          !isOwnedBy(snapshot.data() as { ownerId?: unknown }, opts.requireOwnerId)
        ) {
          throw new Error('Report not found');
        }

        const existing = normalizeReportDoc(snapshot.data() as Record<string, unknown>) as Report & {
          previousHtml?: string;
        };

        // Resolve the target html (all tx reads happen before any tx writes).
        let targetHtml: string;
        if (opts.versionId) {
          const versionSnap = await tx.get(reportRef.collection('versions').doc(opts.versionId));
          const versionHtml = versionSnap.exists ? (versionSnap.data()?.html as string | undefined) : undefined;
          if (!versionHtml) {
            throw new Error('Version not found');
          }
          targetHtml = versionHtml;
        } else {
          if (!existing.previousHtml) {
            throw new Error('No previous version available');
          }
          targetHtml = existing.previousHtml;
        }

        // Snapshot the current head into history before overwriting it.
        const versionWrites = await stageVersionCapture(tx, reportRef, existing, {
          savedBy: opts.savedBy,
          reason: 'restore',
        });

        const updatedFields: Record<string, unknown> = {
          html: targetHtml,
          // The outgoing head remains the one-step backup (reversible swap).
          previousHtml: existing.html,
          updatedAt: new Date().toISOString(),
        };
        // REPORT-004: lifecycle restore lands in the SAME transaction as the
        // html swap — a rollback can never leave the restored html carrying
        // the rejected revision's review status or gate receipt.
        if (opts.alsoSet) {
          for (const [key, value] of Object.entries(opts.alsoSet)) {
            if (value !== undefined) updatedFields[key] = value;
          }
        }

        tx.update(reportRef, updatedFields);
        for (const write of versionWrites) tx.set(write.ref, write.data);
        return { ...existing, ...updatedFields } as Report;
      }),
      'restoreReportVersion.transaction'
    );

    log.info('Report restored', { id, versionId: opts.versionId, savedBy: opts.savedBy });
    return restored;
  } catch (error) {
    if (
      error instanceof Error &&
      (error.message === 'Report not found' ||
        error.message === 'No previous version available' ||
        error.message === 'Version not found')
    ) {
      throw error;
    }
    log.error('Failed to restore report', error instanceof Error ? error : new Error(String(error)));
    throw error;
  }
}

/**
 * Verify that every requested report exists and belongs to the same user.
 *
 * Callers use this as one fail-closed authorization preflight before a single
 * or bulk destructive operation. The boolean deliberately does not distinguish
 * a missing report from an owner mismatch, so request IDs cannot be used to
 * probe another user's report inventory.
 */
export async function reportsBelongToOwner(ids: readonly string[], ownerId: string): Promise<boolean> {
  if (!ownerId || ids.length === 0) return false;

  try {
    const snapshots = await Promise.all(
      ids.map((id) => withDeadline(reportsCol().doc(id).get(), `reportsBelongToOwner.get[${id}]`))
    );
    return snapshots.every((snapshot) => snapshot.exists && snapshot.data()?.ownerId === ownerId);
  } catch (error) {
    log.error('Failed to authorize report ownership', error instanceof Error ? error : new Error(String(error)), {
      count: ids.length,
    });
    throw error;
  }
}

/**
 * Delete a report by ID.
 *
 * @param id - The report ID to delete
 * @throws Error if Firestore delete fails
 */
export async function deleteReport(id: string): Promise<void> {
  try {
    // Firestore does not cascade a parent document delete into subcollections.
    // Reports keep immutable history under `versions`, so use the Admin SDK's
    // recursive delete to avoid leaving inaccessible version documents behind.
    await withDeadline(db.recursiveDelete(reportsCol().doc(id)), 'deleteReport.recursiveDelete');
    log.info('Report deleted', { id });
  } catch (error) {
    log.error('Failed to delete report', error instanceof Error ? error : new Error(String(error)));
    throw error;
  }
}

/**
 * Delete multiple reports by IDs.
 *
 * @param ids - Array of report IDs to delete
 * @throws Error if any Firestore delete fails
 */
export async function deleteReports(ids: string[]): Promise<void> {
  try {
    const uniqueIds = Array.from(new Set(ids));
    await Promise.all(
      uniqueIds.map((id) =>
        withDeadline(db.recursiveDelete(reportsCol().doc(id)), `deleteReports.recursiveDelete[${id}]`)
      )
    );
    log.info('Reports bulk deleted', { count: uniqueIds.length });
  } catch (error) {
    log.error('Failed to bulk delete reports', error instanceof Error ? error : new Error(String(error)));
    throw error;
  }
}
