/**
 * @file ai/tools/cypher-tools.ts
 * @description AI tools for Cypher query generation and explanation
 *
 * Provides capabilities for:
 * - Generating Cypher queries from natural language
 * - Explaining what a Cypher query does
 * - Validating Cypher queries for safety
 * - Listing available entity types and relationships
 *
 * @author Radarist Team
 * @created 2026-01-21
 */

import { SchemaType, type FunctionDeclaration } from '@google/generative-ai';
import {
  parseNaturalLanguageQuery,
  generateCypherQuery,
  isSafeQuery,
  getExampleQueries,
  type GeneratedQuery,
  type ParsedQuery,
} from '@/lib/graph/nl-to-cypher';
import { runRawReadQuery, sanitizeNeo4jErrorMessage } from '@/lib/graph/neo4j-client';
import { inspectCypherReadQuery, RAW_CYPHER_LIMITS } from '@/lib/graph/cypher-read-policy';
import { CLAIM_RELATION_PREDICATES } from '@/lib/graph/relation-registry';
import { createLogger } from '@/lib/logger';

const log = createLogger('ai/cypher-tools');

function sanitizedToolError(error: unknown, fallback: string): { message: string; logError?: Error } {
  if (!(error instanceof Error)) return { message: fallback };
  const message = sanitizeNeo4jErrorMessage(error.message);
  return { message, logError: new Error(message) };
}

// ============================================================================
// Tool Definitions for Cypher Operations
// ============================================================================

export const CYPHER_TOOLS: FunctionDeclaration[] = [
  {
    name: 'generateCypher',
    description: `Generate a Cypher query from a natural language question about the knowledge graph. Translates plain English into graph database queries. Can optionally execute the query immediately.

WHEN TO USE THIS TOOL:
- "Give me the cypher to find all relations of [entity]"
- "Write a query to get companies related to [technology]"
- "Generate cypher for technologies connected to [strategy]"
- "What's the query to find [specific pattern]?"
- When user wants to explore graph relationships programmatically
- When building custom reports or analyses

WHAT IT DOES:
1. Parses natural language question
2. Generates valid Cypher query
3. Explains what the query does
4. Optionally executes and returns results

EXAMPLE - Generate without executing:
{
  "question": "find all technologies used by companies in healthcare",
  "execute": false
}

EXAMPLE - Generate and execute:
{
  "question": "get all relations of the technology Kubernetes",
  "execute": true,
  "limit": 30
}

SUPPORTS QUERIES LIKE:
- "All relations of entity X" → finds connected nodes
- "Companies that provide/use technology Y" → relationship patterns
- "Technologies aligned with strategy Z" → strategic alignment
- "Shortest path between A and B" → path finding

RETURNS: Cypher query string, explanation of what it does, and optional results if execute=true.

TIP: Use execute=false first to preview the query, then execute=true if it looks correct. Use getCypherSchema to see available node types and relationships.`,
    parameters: {
      type: SchemaType.OBJECT,
      properties: {
        question: {
          type: SchemaType.STRING,
          description:
            "Natural language question about what to find in the graph. Be specific about entities and relationships you're looking for.",
        },
        execute: {
          type: SchemaType.BOOLEAN,
          description:
            'If true, execute the query and return results. If false (default), return the Cypher query without executing. Recommend false first to preview.',
        },
        limit: {
          type: SchemaType.NUMBER,
          description:
            'Max results if executing (default: 20, max: 100). Increase for comprehensive queries, decrease for quick lookups.',
        },
      },
      required: ['question'],
    },
  },
  {
    name: 'explainCypher',
    description: `Explain what a Cypher query does in plain English. Breaks down the query into understandable components. Useful for understanding existing queries or debugging.

WHEN TO USE THIS TOOL:
- "What does this Cypher query do?"
- "Explain this query: MATCH (n)..."
- User pastes a Cypher query and wants to understand it
- Troubleshooting why a query isn't returning expected results
- Learning Cypher by understanding example queries

EXAMPLE:
{
  "cypher": "MATCH (c:Company)-[:USES]->(t:Technology) WHERE t.name = 'Kubernetes' RETURN c.name, t.name LIMIT 10"
}

RETURNS:
- Plain English explanation of what the query does
- Breakdown of components (MATCH patterns, WHERE filters, RETURN clauses)
- List of operations used (COUNT, DISTINCT, ORDER BY, etc.)
- Safety warning if query contains destructive operations

ALSO USEFUL FOR:
- Understanding queries generated by generateCypher
- Verifying a query does what you expect before executingit
- Learning Cypher syntax through examples`,
    parameters: {
      type: SchemaType.OBJECT,
      properties: {
        cypher: {
          type: SchemaType.STRING,
          description: 'The Cypher query to explain. Can be multi-line.',
        },
      },
      required: ['cypher'],
    },
  },
  {
    name: 'validateCypher',
    description: `Validate if a Cypher query is safe to execute. Checks for destructive operations and potential performance issues. Use this before executing user-provided queries.

WHEN TO USE THIS TOOL:
- Before running a query provided by the user
- "Is this query safe?" or "Check this Cypher"
- When user wants to run a custom query
- Validating queries from external sources

CHECKS FOR:
- Destructive operations: DELETE, DROP, CREATE, SET, MERGE, REMOVE
- Unbounded variable-length paths (performance risk)
- Missing LIMIT clauses (may return huge result sets)

EXAMPLE:
{
  "cypher": "MATCH (n) DELETE n"
}

RETURNS:
- isValid: Whether query is structurally acceptable
- isSafe: Whether query is READ-only (no data modification)
- issues: Array of detected problems with explanations

SAFETY LEVELS:
- Safe (READ-only): Can execute freely with executeCypher
- Unsafe (WRITE): Contains CREATE, SET, MERGE - can modify data
- Dangerous: Contains DELETE, DROP, REMOVE - can destroy data

TIP: Always validate user-provided queries before execution. executeCypher only allows safe (READ-only) queries.`,
    parameters: {
      type: SchemaType.OBJECT,
      properties: {
        cypher: {
          type: SchemaType.STRING,
          description: 'The Cypher query to validate for safety and potential issues.',
        },
      },
      required: ['cypher'],
    },
  },
  {
    name: 'getCypherSchema',
    description: `Get the supported graph-query contract: canonical entity labels, Relation-writer predicates, common structural/document/radar edges, properties, and example queries. Essential reference for building Cypher queries.

WHEN TO USE THIS TOOL:
- "What node types are in the graph?"
- "What relationships exist between entities?"
- "Show me the graph schema"
- "What properties does [entity type] have?"
- Before using generateCypher to understand available options
- When user asks about graph structure

RETURNS:
- Node Types: PascalCase labels for entity nodes plus label-only Document and RadarPlacement nodes
- Relation-writer predicates: USES, ENABLES, SOLVES, ALIGNS_WITH, IMPACTS, COMPETES_WITH, EVALUATES, RELATED_TO, etc.
- Structural edges: assertion provenance, document links, and radar-placement wiring in a separate list
- Properties: List of queryable fields per node type
- Example Queries: Ready-to-use Cypher patterns for common tasks

IMPORTANT: MATCH patterns use PascalCase labels — MATCH (t:Technology); lowercase labels like :technology match 0 nodes. Entity nodes use camelCase entityType values such as {entityType: 'orgUnit'}. Document and RadarPlacement are label-only and do not store entityType.

EXAMPLE (no parameters needed):
{}

USE CASE EXAMPLES:
1. User asks "what can I query?" → getCypherSchema to show options
2. Building a query → check schema for correct node/relationship types
3. User confused about graph structure → show schema for orientation

TIP: Call this before generateCypher when user is unfamiliar with the graph structure. The example queries are excellent starting points.`,
    parameters: {
      type: SchemaType.OBJECT,
      properties: {},
      required: [],
    },
  },
  {
    name: 'executeCypher',
    description: `Execute a raw Cypher query against the knowledge graph database. Only READ-ONLY queries are allowed - no data modification. Use this when user provides a specific Cypher query to run.

WHEN TO USE THIS TOOL:
- User pastes a Cypher query: "Run this: MATCH (n)..."
- "Execute this query" with provided Cypher
- After generateCypher to run the generated query
- For custom queries not covered by other tools

SAFETY RESTRICTIONS:
- Only READ queries allowed (MATCH, RETURN, WHERE, etc.)
- Procedures, external loading, administration, transaction control, and dynamic APOC Cypher are blocked
- Results stop at 100 records or 256 KiB, and queries stop after 10 seconds
- Use validateCypher first if unsure about a query

EXAMPLE - Simple query:
{
  "cypher": "MATCH (t:Technology) RETURN t.name, t.category LIMIT 20"
}

EXAMPLE - Parameterized query:
{
  "cypher": "MATCH (c:Company)-[:USES]->(t:Technology) WHERE t.name = $techName RETURN c.name",
  "params": { "techName": "Kubernetes" }
}

RETURNS:
- results: Array of matched records
- resultCount: Number of results
- executionTimeMs: Query performance
- truncated, truncationReasons, limits: Explicit partial-result metadata

WORKFLOW OPTIONS:
1. Natural language → generateCypher(execute=true) - all in one
2. Natural language → generateCypher(execute=false) → executeCypher - review first
3. Direct Cypher → validateCypher → executeCypher - safe execution of user queries

TIP: Use parameterized queries ($param) for cleaner, safer queries. Check execution time to optimize slow queries.`,
    parameters: {
      type: SchemaType.OBJECT,
      properties: {
        cypher: {
          type: SchemaType.STRING,
          description: 'The Cypher query to execute. MUST be READ-only (MATCH/RETURN/WHERE). No CREATE/DELETE/SET.',
        },
        params: {
          type: SchemaType.OBJECT,
          properties: {},
          description:
            'Optional query parameters. Use $paramName in query, provide values here as { paramName: value }.',
        },
      },
      required: ['cypher'],
    },
  },
];

// ============================================================================
// Result Types
// ============================================================================

export interface GenerateCypherResult {
  success: boolean;
  cypher?: string;
  explanation?: string;
  params?: Record<string, unknown>;
  parsedQuery?: ParsedQuery;
  results?: unknown[];
  resultCount?: number;
  executionTimeMs?: number;
  executed?: boolean;
  truncated?: boolean;
  truncationReasons?: string[];
  limits?: typeof RAW_CYPHER_LIMITS;
  payloadBytes?: number;
  error?: string;
}

export interface ExplainCypherResult {
  success: boolean;
  explanation?: string;
  components?: {
    matchClauses: string[];
    whereClauses: string[];
    returnClauses: string[];
    operations: string[];
  };
  error?: string;
}

export interface ValidateCypherResult {
  success: boolean;
  isValid?: boolean;
  isSafe?: boolean;
  issues?: string[];
  error?: string;
}

export interface CypherSchemaResult {
  success: boolean;
  schema?: {
    nodeTypes: Array<{
      /** Logical schema key. Entity nodes use this as their entityType value. */
      type: string;
      /** Node label (PascalCase — what MATCH patterns must use) */
      label: string;
      /** Stored entityType value, or null for label-only structural nodes. */
      entityTypeProperty: string | null;
      description: string;
      properties: string[];
    }>;
    relationshipTypes: Array<{
      type: string;
      description: string;
      validConnections: string;
    }>;
    structuralRelationshipTypes: Array<{
      type: string;
      category: 'assertion' | 'document' | 'radar';
      description: string;
    }>;
    exampleQueries: Array<{
      intent: string;
      examples: string[];
    }>;
  };
  error?: string;
}

export interface ExecuteCypherResult {
  success: boolean;
  results?: unknown[];
  resultCount?: number;
  executionTimeMs?: number;
  truncated?: boolean;
  truncationReasons?: string[];
  limits?: typeof RAW_CYPHER_LIMITS;
  payloadBytes?: number;
  error?: string;
}

interface BoundedCypherExecution {
  records: Record<string, unknown>[];
  executionTimeMs: number;
  truncated: boolean;
  truncationReasons: string[];
  payloadBytes: number;
}

async function executeBoundedCypherRead(
  cypher: string,
  params: Record<string, unknown>,
  surface: 'raw' | 'generated'
): Promise<BoundedCypherExecution> {
  const startTime = Date.now();
  const queryResult = await runRawReadQuery(cypher, params, {
    transactionTimeoutMs: RAW_CYPHER_LIMITS.transactionTimeoutMs,
    wallTimeoutMs: RAW_CYPHER_LIMITS.wallTimeoutMs,
    maxRecords: RAW_CYPHER_LIMITS.records,
    maxPayloadBytes: RAW_CYPHER_LIMITS.responseBytes,
    recordMode: 'native',
    metadata: { application: 'radarist', surface: `ai-cypher-${surface}` },
  });

  return {
    records: queryResult.nativeRecords ?? [],
    executionTimeMs: Date.now() - startTime,
    truncated: queryResult.truncated,
    truncationReasons: queryResult.truncationReasons,
    payloadBytes: queryResult.payloadBytes ?? 2,
  };
}

// ============================================================================
// Schema Information
// ============================================================================

// H2: node LABELS are PascalCase (`:Technology` — `:technology` matches 0
// nodes). Entity nodes store camelCase entityType values; Document and
// RadarPlacement are label-only graph nodes. The schema this tool emits is
// what the LLM copies into real queries, so the distinction is explicit.
const NODE_TYPES = [
  {
    type: 'technology',
    label: 'Technology',
    entityTypeProperty: 'technology',
    description: 'Technologies, frameworks, platforms, tools',
    properties: ['name', 'description', 'category', 'tags', 'websiteUrl'],
  },
  {
    type: 'company',
    label: 'Company',
    entityTypeProperty: 'company',
    description: 'Business organizations, vendors, partners, competitors',
    properties: ['name', 'description', 'industry', 'type', 'status', 'size'],
  },
  {
    type: 'useCase',
    label: 'UseCase',
    entityTypeProperty: 'useCase',
    description: 'Business use cases and applications',
    properties: ['title', 'description', 'category', 'status'],
  },
  {
    type: 'prototype',
    label: 'Prototype',
    entityTypeProperty: 'prototype',
    description: 'Proof of concept implementations',
    properties: ['name', 'description', 'status', 'team'],
  },
  {
    type: 'strategy',
    label: 'Strategy',
    entityTypeProperty: 'strategy',
    description: 'Business strategies and initiatives',
    properties: ['name', 'description', 'mainDirectives'],
  },
  {
    type: 'signal',
    label: 'Signal',
    entityTypeProperty: 'signal',
    description: 'Market signals, news, and trends',
    properties: ['title', 'description', 'source', 'signalType', 'status'],
  },
  {
    type: 'orgUnit',
    label: 'OrgUnit',
    entityTypeProperty: 'orgUnit',
    description: 'Organizational units and departments',
    properties: ['name', 'description', 'level', 'type'],
  },
  {
    type: 'initiative',
    label: 'Initiative',
    entityTypeProperty: 'initiative',
    description: 'Business initiatives and projects',
    properties: ['name', 'description', 'status', 'priority'],
  },
  {
    type: 'painPoint',
    label: 'PainPoint',
    entityTypeProperty: 'painPoint',
    description: 'Business challenges and pain points',
    properties: ['title', 'description', 'severity', 'status'],
  },
  {
    type: 'document',
    label: 'Document',
    entityTypeProperty: null,
    description: 'Research documents and other durable source artifacts',
    properties: ['title', 'description', 'type', 'status', 'tags'],
  },
  {
    type: 'radarPlacement',
    label: 'RadarPlacement',
    entityTypeProperty: null,
    description: 'Technology positions on a radar, including ring and quadrant',
    properties: ['technologyId', 'radarId', 'ring', 'quadrant', 'maturity', 'status'],
  },
];

const RELATIONSHIP_DESCRIPTIONS: Record<string, string> = {
  USES: 'Entity uses or adopts another entity',
  ENABLES: 'Entity enables or powers another entity',
  SOLVES: 'Entity solves a pain point',
  ADDRESSES: 'Entity addresses a need or pain point',
  ALIGNS_WITH: 'Entity aligns with a strategy',
  IMPACTS: 'Entity impacts another entity',
  COMPETES_WITH: 'Entities compete directly',
  VENDOR: 'Company is a vendor for another entity',
  PARTNER: 'Entities have a partner relationship',
  EVALUATES: 'Entity evaluates another entity',
  RELATED_TO: 'Canonical fallback for relation types without a dedicated predicate',
};

// Derive the advertised vocabulary from the writer registry. A hand-maintained
// list previously taught agents phantom predicates that return empty results on
// a fresh graph.
const RELATIONSHIP_TYPES = CLAIM_RELATION_PREDICATES.map((type) => ({
  type,
  description: RELATIONSHIP_DESCRIPTIONS[type] ?? `Canonical ${type.replace(/_/g, ' ').toLowerCase()} relation`,
  validConnections: 'See the Relation source and target entity snapshots',
}));

const STRUCTURAL_RELATIONSHIP_TYPES: NonNullable<CypherSchemaResult['schema']>['structuralRelationshipTypes'] = [
  { type: 'ABOUT_SUBJECT', category: 'assertion', description: 'Assertion subject role' },
  { type: 'ABOUT_OBJECT', category: 'assertion', description: 'Assertion object role' },
  { type: 'HAS_PREDICATE', category: 'assertion', description: 'Assertion predicate role' },
  { type: 'ASSERTED_BY', category: 'assertion', description: 'Assertion asserter role' },
  { type: 'SUPPORTED_BY', category: 'assertion', description: 'Assertion evidence provenance' },
  { type: 'MENTIONS', category: 'document', description: 'Document or chunk mentions an entity' },
  { type: 'DOCUMENTED_BY', category: 'document', description: 'Entity documentation link' },
  { type: 'HAS_EVIDENCE', category: 'document', description: 'Entity evidence-document link' },
  { type: 'CONTAINS', category: 'document', description: 'Document contains a chunk' },
  { type: 'PLACES', category: 'radar', description: 'RadarPlacement points to a Technology' },
  { type: 'ON_RADAR', category: 'radar', description: 'RadarPlacement belongs to a Radar' },
];

// ============================================================================
// Execution Functions
// ============================================================================

/**
 * Generate a Cypher query from natural language and optionally execute it
 */
export async function executeGenerateCypher(args: Record<string, unknown>): Promise<GenerateCypherResult> {
  try {
    const question = args.question;
    const execute = args.execute === true;
    const requestedLimit = typeof args.limit === 'number' && Number.isFinite(args.limit) ? Math.floor(args.limit) : 20;
    const limit = Math.max(1, Math.min(requestedLimit, RAW_CYPHER_LIMITS.records));

    if (typeof question !== 'string' || question.trim().length === 0) {
      return { success: false, error: 'question is required' };
    }

    // Parse the natural language query
    const parsed = await parseNaturalLanguageQuery(question);

    // Apply limit override
    if (parsed.filters) {
      parsed.filters.limit = limit;
    } else {
      parsed.filters = { limit };
    }

    // Generate the Cypher query
    const generated: GeneratedQuery = generateCypherQuery(parsed);

    const result: GenerateCypherResult = {
      success: true,
      cypher: generated.cypher.trim(),
      explanation: generated.explanation,
      params: generated.params,
      parsedQuery: parsed,
      executed: false,
    };

    // Optionally execute the query
    if (execute) {
      if (!isSafeQuery(generated.cypher)) {
        return {
          success: false,
          error: 'Generated query contains potentially destructive operations and cannot be executed',
          cypher: generated.cypher.trim(),
          explanation: generated.explanation,
        };
      }

      try {
        const queryResult = await executeBoundedCypherRead(generated.cypher, generated.params, 'generated');

        result.results = queryResult.records;
        result.resultCount = queryResult.records.length;
        result.executionTimeMs = queryResult.executionTimeMs;
        result.truncated = queryResult.truncated;
        result.truncationReasons = queryResult.truncationReasons;
        result.limits = RAW_CYPHER_LIMITS;
        result.payloadBytes = queryResult.payloadBytes;
        result.executed = true;
      } catch (execError) {
        const message = execError instanceof Error ? sanitizeNeo4jErrorMessage(execError.message) : 'Unknown error';
        result.error = `Query generated but execution failed: ${message}`;
        result.executed = false;
      }
    }

    return result;
  } catch (error) {
    const sanitized = sanitizedToolError(error, 'Failed to generate Cypher query');
    log.error('generateCypher error', sanitized.logError);
    return {
      success: false,
      error: sanitized.message,
    };
  }
}

/**
 * Explain what a Cypher query does
 */
export async function executeExplainCypher(args: Record<string, unknown>): Promise<ExplainCypherResult> {
  try {
    const cypher = args.cypher as string;

    if (!cypher) {
      return { success: false, error: 'cypher is required' };
    }

    // Parse the query to extract components
    const components = {
      matchClauses: [] as string[],
      whereClauses: [] as string[],
      returnClauses: [] as string[],
      operations: [] as string[],
    };

    // Extract MATCH clauses
    const matchMatches = cypher.match(/MATCH\s+([^WHERE|RETURN|WITH|ORDER|LIMIT]+)/gi);
    if (matchMatches) {
      components.matchClauses = matchMatches.map((m) => m.replace(/MATCH\s+/i, '').trim());
    }

    // Extract WHERE clauses
    const whereMatches = cypher.match(/WHERE\s+([^RETURN|WITH|ORDER|LIMIT]+)/gi);
    if (whereMatches) {
      components.whereClauses = whereMatches.map((m) => m.replace(/WHERE\s+/i, '').trim());
    }

    // Extract RETURN clauses
    const returnMatches = cypher.match(/RETURN\s+([^ORDER|LIMIT]+)/gi);
    if (returnMatches) {
      components.returnClauses = returnMatches.map((m) => m.replace(/RETURN\s+/i, '').trim());
    }

    // Identify operations
    if (/\bshortestPath\b/i.test(cypher)) {
      components.operations.push('Finds shortest path between nodes');
    }
    if (/\ballShortestPaths\b/i.test(cypher)) {
      components.operations.push('Finds all shortest paths between nodes');
    }
    if (/\bCOUNT\b/i.test(cypher)) {
      components.operations.push('Counts results');
    }
    if (/\bCOLLECT\b/i.test(cypher)) {
      components.operations.push('Aggregates results into lists');
    }
    if (/\bDISTINCT\b/i.test(cypher)) {
      components.operations.push('Returns unique results only');
    }
    if (/\bORDER BY\b/i.test(cypher)) {
      components.operations.push('Sorts results');
    }
    if (/\bLIMIT\b/i.test(cypher)) {
      components.operations.push('Limits number of results');
    }

    // Build explanation
    let explanation = 'This Cypher query ';

    if (components.matchClauses.length > 0) {
      explanation += `searches for patterns: ${components.matchClauses.join(', ')}. `;
    }

    if (components.whereClauses.length > 0) {
      explanation += `It filters results where: ${components.whereClauses.join(' AND ')}. `;
    }

    if (components.returnClauses.length > 0) {
      explanation += `It returns: ${components.returnClauses.join(', ')}. `;
    }

    if (components.operations.length > 0) {
      explanation += `Additional operations: ${components.operations.join(', ')}.`;
    }

    // Check safety
    if (!isSafeQuery(cypher)) {
      explanation +=
        ' WARNING: This query contains potentially destructive operations (CREATE, DELETE, SET, etc.) and should be used with caution.';
    }

    return {
      success: true,
      explanation: explanation.trim(),
      components,
    };
  } catch (error) {
    const sanitized = sanitizedToolError(error, 'Failed to explain Cypher query');
    log.error('explainCypher error', sanitized.logError);
    return {
      success: false,
      error: sanitized.message,
    };
  }
}

/**
 * Validate if a Cypher query is safe to execute
 */
export async function executeValidateCypher(args: Record<string, unknown>): Promise<ValidateCypherResult> {
  try {
    const cypher = args.cypher as string;

    if (!cypher) {
      return { success: false, error: 'cypher is required' };
    }

    const issues: string[] = [];
    const policy = inspectCypherReadQuery(cypher);
    if (!policy.allowed && policy.reason) issues.push(policy.reason);

    // Check for potential performance issues
    if (/\[\*\]/.test(cypher) && !/\[\*\d+\.\.\d+\]/.test(cypher)) {
      issues.push('Contains unbounded variable-length path - may cause performance issues');
    }

    if (!/\bLIMIT\b/i.test(cypher) && /\bMATCH\b/i.test(cypher)) {
      issues.push('No LIMIT clause - may return large result sets');
    }

    const isSafe = policy.allowed;
    const isValid = !['EMPTY_QUERY', 'UNTERMINATED_LITERAL', 'MULTIPLE_STATEMENTS'].includes(policy.code ?? '');

    return {
      success: true,
      isValid,
      isSafe,
      issues: issues.length > 0 ? issues : undefined,
    };
  } catch (error) {
    const sanitized = sanitizedToolError(error, 'Failed to validate Cypher query');
    log.error('validateCypher error', sanitized.logError);
    return {
      success: false,
      error: sanitized.message,
    };
  }
}

/**
 * Get the knowledge graph schema
 */
export async function executeGetCypherSchema(_args: Record<string, unknown>): Promise<CypherSchemaResult> {
  try {
    const exampleQueries = getExampleQueries();

    return {
      success: true,
      schema: {
        nodeTypes: NODE_TYPES,
        relationshipTypes: RELATIONSHIP_TYPES,
        structuralRelationshipTypes: STRUCTURAL_RELATIONSHIP_TYPES,
        exampleQueries,
      },
    };
  } catch (error) {
    const sanitized = sanitizedToolError(error, 'Failed to get schema');
    log.error('getCypherSchema error', sanitized.logError);
    return {
      success: false,
      error: sanitized.message,
    };
  }
}

/**
 * Execute a raw Cypher query (READ-only)
 */
export async function executeExecuteCypher(args: Record<string, unknown>): Promise<ExecuteCypherResult> {
  try {
    const cypher = args.cypher;
    const params = args.params ?? {};

    if (typeof cypher !== 'string' || cypher.trim().length === 0) {
      return { success: false, error: 'cypher is required' };
    }
    if (params === null || typeof params !== 'object' || Array.isArray(params)) {
      return { success: false, error: 'params must be an object' };
    }

    const policy = inspectCypherReadQuery(cypher, params);
    if (!policy.allowed) {
      return {
        success: false,
        error: policy.reason ?? 'Only bounded read queries are allowed.',
      };
    }

    const queryResult = await executeBoundedCypherRead(cypher, params as Record<string, unknown>, 'raw');

    return {
      success: true,
      results: queryResult.records,
      resultCount: queryResult.records.length,
      executionTimeMs: queryResult.executionTimeMs,
      truncated: queryResult.truncated,
      truncationReasons: queryResult.truncationReasons,
      limits: RAW_CYPHER_LIMITS,
      payloadBytes: queryResult.payloadBytes,
    };
  } catch (error) {
    const sanitized = sanitizedToolError(error, 'Failed to execute Cypher query');
    log.error('executeCypher error', sanitized.logError);
    return {
      success: false,
      error: sanitized.message,
    };
  }
}
