/**
 * @file app/share/report/[id]/page.tsx
 * @description Public share page for reports
 *
 * This is a server component that:
 * - Fetches the report directly from Firestore (no API call, no auth)
 * - Renders parser-normalized static report HTML in a zero-capability iframe
 * - Sets Open Graph meta tags for link previews
 * - Marks the content as AI-generated (EU AI Act Art 50(2)/(4)): a machine-readable
 *   `<meta name="ai-generated">` + schema.org JSON-LD, plus a visible footer disclaimer.
 *   These live in the parent document, outside the report's sandboxed iframe.
 *
 * SECURITY: report HTML is parser-normalized in `PublicReportPreview` before it
 * enters an exact empty sandbox. Scripts, event handlers, external resources,
 * navigation surfaces, active embeds, and meta refresh are removed, while a
 * deny-by-default CSP is inserted as the first child policy. This matches the
 * authenticated viewer's SEC-003 boundary: an opaque origin alone is not
 * sufficient because opaque scripts can still self-navigate and egress.
 *
 * @author Radarist Team
 * @created 2026-02-23
 */

import type { Metadata } from 'next';
import { getReportById } from '@/lib/reports';
import { PublicReportPreview } from './public-report-preview';

// ============================================================================
// Metadata
// ============================================================================

/**
 * Generate metadata for the share page.
 * Sets Open Graph tags for link preview when sharing the URL.
 */
export async function generateMetadata({ params }: { params: Promise<{ id: string }> }): Promise<Metadata> {
  const { id } = await params;
  const report = await getReportById(id);

  if (!report) {
    return {
      title: 'Report Not Found',
      description: 'This report may have been deleted or the link is invalid.',
    };
  }

  // REPORT-001: mirror the page body's fail-closed order. A needs-review draft
  // must not leak its real title/description/ogImage through <head> metadata
  // even when a stale shared:true survives (e.g. a shared report whose later
  // revision failed the design gate).
  if (report.reviewStatus === 'needs-review') {
    return {
      title: 'Report Not Available',
      description: 'This report is a draft pending review and is not publicly available.',
    };
  }

  // Public access requires an explicit boolean opt-in. Legacy or malformed
  // records must fail closed instead of exposing their metadata.
  if (report.shared !== true) {
    return {
      title: 'Report Not Shared',
      description: 'This report is not publicly shared.',
    };
  }

  const description = report.metadata?.description ?? 'Shared report generated by Radarist.';

  return {
    title: report.title,
    description,
    openGraph: {
      title: report.title,
      description,
      images: report.metadata?.ogImage ? [report.metadata.ogImage] : [],
    },
  };
}

// ============================================================================
// Provenance
// ============================================================================

/**
 * Formats an ISO timestamp for the provenance footer, or returns undefined for
 * missing/unparseable input. Local (server-safe) — the hooks' formatDate lives
 * in a 'use client' module and cannot be called from this server component.
 */
function formatProvenanceDate(iso: string | undefined): string | undefined {
  if (!iso) return undefined;
  const date = new Date(iso);
  if (Number.isNaN(date.getTime())) return undefined;
  return date.toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' });
}

/** Serialize JSON-LD without allowing user-controlled strings to close its script tag. */
function serializeJsonLd(value: unknown): string {
  const escapes: Record<string, string> = {
    '<': '\\u003c',
    '>': '\\u003e',
    '&': '\\u0026',
    '\u2028': '\\u2028',
    '\u2029': '\\u2029',
  };
  return JSON.stringify(value).replace(/[<>&\u2028\u2029]/g, (character) => escapes[character]);
}

// ============================================================================
// Page Component
// ============================================================================

/**
 * Public share page for reports.
 *
 * This page has NO auth requirement — it is intentionally public.
 * The report HTML is rendered through `srcDoc` in a sandboxed iframe, followed
 * by a minimal parent-document footer.
 *
 * @param props.params - Route params containing the report ID
 */
export default async function ShareReportPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const report = await getReportById(id);

  if (!report) {
    return (
      <div
        style={{
          textAlign: 'center',
          padding: '4rem',
          fontFamily: 'system-ui, -apple-system, sans-serif',
        }}
      >
        <h1 style={{ fontSize: '1.5rem', marginBottom: '1rem' }}>Report Not Found</h1>
        <p style={{ color: '#666' }}>This report may have been deleted or the link is invalid.</p>
      </div>
    );
  }

  // REPORT-001: a report whose design review did not pass is a retained
  // `needs-review` draft, not a final shareable artifact. Fail closed even if it
  // was somehow toggled shared, so a design-failing report is never served as a
  // final public report. Absent status → published (back-compat).
  if (report.reviewStatus === 'needs-review') {
    return (
      <div
        style={{
          textAlign: 'center',
          padding: '4rem',
          fontFamily: 'system-ui, -apple-system, sans-serif',
        }}
      >
        <h1 style={{ fontSize: '1.5rem', marginBottom: '1rem' }}>Report Not Available</h1>
        <p style={{ color: '#666' }}>This report is a draft pending review and is not publicly available.</p>
      </div>
    );
  }

  // Public access requires an explicit boolean opt-in. Legacy or malformed
  // records must fail closed instead of exposing their contents.
  if (report.shared !== true) {
    return (
      <div
        style={{
          textAlign: 'center',
          padding: '4rem',
          fontFamily: 'system-ui, -apple-system, sans-serif',
        }}
      >
        <h1 style={{ fontSize: '1.5rem', marginBottom: '1rem' }}>Report Not Shared</h1>
        <p style={{ color: '#666' }}>This report is not publicly shared. Ask the report owner to enable sharing.</p>
      </div>
    );
  }

  if (!report.html) {
    return (
      <div
        style={{
          textAlign: 'center',
          padding: '4rem',
          fontFamily: 'system-ui, -apple-system, sans-serif',
        }}
      >
        <h1 style={{ fontSize: '1.5rem', marginBottom: '1rem' }}>{report.title ?? 'Report'}</h1>
        <p style={{ color: '#666' }}>This report is still being generated. Please check back shortly.</p>
      </div>
    );
  }

  // Provenance is built from structured report fields (never report.html) and
  // rendered as React text outside the sandbox. Missing segments are skipped.
  const provenanceSegments: string[] = [];
  const snapshotDate = formatProvenanceDate(report.metadata?.dataSnapshotAt);
  if (snapshotDate) provenanceSegments.push(`Data as of ${snapshotDate}`);
  if (report.entityIds) {
    provenanceSegments.push(
      `${report.entityIds.length} linked ${report.entityIds.length === 1 ? 'entity' : 'entities'}`
    );
  }
  provenanceSegments.push(`generated by ${report.agentType ?? 'agent'}`);

  // Machine-readable AI-generation marker (Art 50(2)). Structured report
  // fields are escaped by serializeJsonLd before rendering outside the sandbox.
  const aiJsonLd = serializeJsonLd({
    '@context': 'https://schema.org',
    '@type': 'CreativeWork',
    creativeWorkStatus: 'AI-generated',
    headline: report.title,
    description: report.metadata?.description,
    author: { '@type': 'Organization', name: 'Radarist Studio' },
    datePublished: report.createdAt,
  });

  return (
    <div
      style={{
        display: 'flex',
        flexDirection: 'column',
        height: '100vh',
        margin: 0,
      }}
    >
      {/* AI-generation disclosure — machine-readable (Art 50(2)), outside the sandboxed HTML */}
      <meta name="ai-generated" content="true" />
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: aiJsonLd }} />
      <PublicReportPreview html={report.html} title={report.title ?? 'Shared report'} />
      <footer
        style={{
          flex: 'none',
          textAlign: 'center',
          padding: '1rem 2rem',
          opacity: 0.7,
          fontSize: '0.8rem',
          fontFamily: 'system-ui, -apple-system, sans-serif',
          borderTop: '1px solid rgba(128,128,128,0.2)',
        }}
      >
        <p style={{ margin: '0 0 0.35rem' }}>
          ✦ This report was generated with AI assistance. Please review it for accuracy.
        </p>
        <p style={{ margin: '0 0 0.35rem', opacity: 0.85 }}>{provenanceSegments.join(' · ')}</p>
        <p style={{ margin: 0, opacity: 0.8 }}>Powered by Radarist</p>
      </footer>
    </div>
  );
}
