/**
 * @file hooks/useBriefing.ts
 * @description TanStack Query hook for briefing-page proactive insights.
 *
 * Fetches `ProactiveInsight` data from `/api/impulse/briefing` for the
 * `BriefingFeed` component. The query is **gated on the Firebase auth
 * state** via `useAuth()` — TanStack Query would otherwise fire on mount
 * before `onAuthStateChanged` has restored the persisted session, hit the
 * "no user" branch, and cache an empty result that nothing re-invalidates.
 * Until the gate opens, the consumer keeps showing the skeleton (`isPending`
 * stays true).
 *
 * Phase 0 step 0.10 of the 2026-05-13 briefing-pipeline cleanup.
 */

import { useEffect, useRef } from 'react';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { useAuth } from '@/components/providers/AuthProvider';
import { fetchWithAuth } from '@/lib/fetch-with-auth';
import { useAgentEventStream } from '@/hooks/useAgentEventStream';
import type { AgentEvent } from '@/lib/schemas/agent-event';

// ============================================================================
// TYPES
// ============================================================================

/**
 * A single proactive insight generated by an Impulse agent.
 */
export interface BriefingInsight {
  id: string;
  type: 'discovery' | 'connection' | 'scoring_change' | 'pattern' | 'narrative';
  title: string;
  summary: string;
  agentName: string;
  confidenceScore: number;
  relatedEntities: { id: string; name: string; type: string }[];
  /**
   * For 'connection' insights: the newly-discovered entity at one end of the
   * graph path. Preferred over `relatedEntities[0]` because Neo4j `collect()`
   * order is not deterministic.
   */
  observedEntityId?: string;
  /**
   * For 'connection' insights: the previously-explored entity at the other
   * end of the graph path.
   */
  exploredEntityId?: string;
  actionable: boolean;
  actionUrl?: string;
  actionLabel?: string;
  createdAt: string;
  /**
   * Whether the current user has liked this insight (thumb-up). Defaults to
   * `false` for older insights and any row where the property is unset.
   * Phase 0 step 0.11 surfaces this from Neo4j; Option A step A.1 will land
   * the toggle endpoints that flip the property.
   */
  liked?: boolean;
  /**
   * Option A step A.0 — structured path data for the detail-page "Why am I
   * seeing this?" breadcrumb. Optional because pre-A.0 connection insights
   * (and all non-connection types) won't carry these. UI falls back to the
   * `summary` string when missing.
   */
  relationshipTypes?: string[];
  sourceRelationTypes?: string[];
  relationshipDirections?: Array<'forward' | 'reverse'>;
  evidenceSummary?: string;
  groundingVersion?: string;
  epistemicKind?: 'observation' | 'inference';
  pathLength?: number;
  exploredAt?: string;
}

/**
 * Summary of token usage for the current billing period.
 */
export interface TokenUsageSummary {
  used: number;
  budget: number;
}

/**
 * Full briefing response including insights and usage metadata.
 */
export interface BriefingData {
  insights: BriefingInsight[];
  tokenUsage: TokenUsageSummary;
}

// ============================================================================
// QUERY KEY FACTORY
// ============================================================================

export const briefingKeys = {
  all: ['briefing'] as const,
  /**
   * UX-046: every briefing key embeds the account uid so a user switch can
   * never serve another account's cached insights. `AccountCacheBoundary`
   * additionally purges the whole cache on auth transitions.
   */
  forUser: (uid: string) => [...briefingKeys.all, uid] as const,
  insights: (uid: string) => [...briefingKeys.forUser(uid), 'insights'] as const,
  /**
   * Per-insight detail query key. Used by `useInsightDetail` (Option A
   * Chunk 1) — the detail-page hook keeps its own cache entry per ID so
   * navigating between rows is instant without re-fetching the full feed.
   */
  detail: (uid: string, insightId: string) => [...briefingKeys.forUser(uid), 'detail', insightId] as const,
  /** UX-051: pipeline status behind the truthful empty states. */
  status: (uid: string) => [...briefingKeys.forUser(uid), 'status'] as const,
};

// ============================================================================
// ERRORS
// ============================================================================

/**
 * How a briefing request failed, so the UI can render the right state
 * (UX-018): an outage is not an empty inbox, and a rate-limit is not a bug.
 */
export type BriefingErrorKind = 'unauthorized' | 'rate-limited' | 'unavailable' | 'error';

/**
 * Typed failure for briefing fetches. Replaces the old swallow-to-empty
 * behaviour that made a Neo4j outage indistinguishable from a clean inbox.
 */
export class BriefingRequestError extends Error {
  readonly status: number;
  readonly kind: BriefingErrorKind;

  constructor(status: number, kind: BriefingErrorKind, message: string) {
    super(message);
    this.name = 'BriefingRequestError';
    this.status = status;
    this.kind = kind;
  }
}

/** Map an HTTP status onto the UI-facing failure kind. */
export function classifyBriefingStatus(status: number): BriefingErrorKind {
  if (status === 401 || status === 403) return 'unauthorized';
  if (status === 429) return 'rate-limited';
  if (status === 503 || status >= 500) return 'unavailable';
  return 'error';
}

// ============================================================================
// FETCH FUNCTION
// ============================================================================

/**
 * Fetch briefing insights from the Impulse briefing API.
 *
 * Auth is enforced by gating the query on `useAuth()` (see the hook below),
 * so by the time this runs we know there's a signed-in user and
 * `fetchWithAuth` will attach a valid ID token.
 *
 * UX-018: failures are no longer swallowed into an empty result. A non-OK
 * response (or an unreachable server) throws a typed {@link BriefingRequestError}
 * so the consumer can distinguish an outage / rate-limit / auth failure from a
 * genuinely empty inbox and offer a retry. The server absorbs transient blips
 * within its bounded-read budget (PERF-008), so an error reaching here means a
 * sustained failure, not a hiccup.
 */
async function fetchBriefingInsights(): Promise<BriefingData> {
  let response: Response;
  try {
    response = await fetchWithAuth('/api/impulse/briefing');
  } catch (networkError) {
    throw new BriefingRequestError(
      0,
      'unavailable',
      networkError instanceof Error ? networkError.message : 'Could not reach the insights service.'
    );
  }

  if (!response.ok) {
    throw new BriefingRequestError(
      response.status,
      classifyBriefingStatus(response.status),
      `Briefing API error: ${response.status}`
    );
  }

  return response.json() as Promise<BriefingData>;
}

// ============================================================================
// HOOK
// ============================================================================

/**
 * useBriefing
 *
 * TanStack Query hook for fetching the briefing page data. Stays in
 * `isPending` while Firebase is restoring the persisted session — the
 * consumer should render the skeleton during that window.
 *
 * On failure the query surfaces `isError` with a {@link BriefingRequestError}
 * (`error.kind`) so the consumer can render an "unavailable" / "rate-limited"
 * state with a retry, instead of the empty-inbox state.
 *
 * @example
 * ```tsx
 * const { data, isPending, isError, error, refetch } = useBriefing();
 * if (isPending) return <CardGridSkeleton cards={4} columns={1} />;
 * if (isError) return <InsightsUnavailable error={error} onRetry={refetch} />;
 * return <BriefingFeed insights={data.insights} />;
 * ```
 */
export function useBriefing() {
  const { user, loading } = useAuth();
  const queryClient = useQueryClient();
  const { events } = useAgentEventStream(!loading && !!user);
  const lastRefreshEventRef = useRef<string | null>(null);
  const query = useQuery({
    queryKey: briefingKeys.insights(user?.uid ?? 'anonymous'),
    queryFn: fetchBriefingInsights,
    enabled: !loading && !!user,
    // UX-046 visible-tab freshness: a bounded interval plus focus refetch
    // replace the old "stale until manual reload" behaviour. The interval
    // pauses automatically while the tab is hidden
    // (refetchIntervalInBackground defaults to false), and a background
    // refetch failure keeps the last-good data on screen (the feed renders
    // a stale-data note instead of swapping to the outage panel).
    staleTime: 30 * 1000,
    refetchInterval: 60 * 1000,
    refetchOnWindowFocus: true,
    // The bounded server read already retries transient errors within its
    // budget (PERF-008), so an error here is a sustained failure. Don't
    // auto-retry — surface it immediately with a manual Retry (UX-018).
    retry: false,
  });

  // A sweep completes outside the page's request lifecycle. Polling remains
  // the outage fallback, but the durable SSE event is the normal fast path:
  // invalidate both the feed and its empty-state status so the first card (or
  // a truthful quiet/failure result) appears without a page reload.
  const refreshEvent = events.findLast((event) => isBriefingRefreshEvent(event, user?.uid));
  useEffect(() => {
    if (!user || !refreshEvent || lastRefreshEventRef.current === refreshEvent.id) return;
    lastRefreshEventRef.current = refreshEvent.id;
    void Promise.all([
      queryClient.invalidateQueries({ queryKey: briefingKeys.insights(user.uid), exact: true }),
      queryClient.invalidateQueries({ queryKey: briefingKeys.status(user.uid), exact: true }),
    ]);
  }, [queryClient, refreshEvent, user]);

  return query;
}

/** Events that can change either the visible feed or its pipeline-state copy. */
export function isBriefingRefreshEvent(event: AgentEvent, userId?: string): boolean {
  if (!userId) return false;
  if (event.type === 'insight.created') return event.userId === userId;
  return event.type === 'agent.completed' && event.agentType === 'sweep-cycle';
}
