/**
 * @file lib/schemas/report.ts
 * @description Zod validation schemas for Report entities
 *
 * Reports are self-contained HTML+CSS documents generated by agents
 * (Creator, Strategist) or created by users. They are stored in the
 * Firestore `reports` collection and served publicly via /share/report/[id].
 *
 * @author Radarist Team
 * @created 2026-02-23
 */

import { z } from 'zod';

import { decodeHtmlEntities } from '@/lib/decode-html-entities';

// ============================================================================
// LIFECYCLE STATE (pure, client-safe — the UI imports from here)
// ============================================================================

/**
 * REPORT-001: a report is a final catalog/share artifact unless its design
 * review explicitly withheld it as `needs-review`. Absent status → published
 * (every pre-REPORT-001 report and any report published without a design brief).
 */
export function isPublishedReport(reviewStatus: unknown): boolean {
  return reviewStatus !== 'needs-review';
}

/** REPORT-002 — the one truthful lifecycle state of a persisted report. */
export type ReportLifecycleState = 'needs-review' | 'private' | 'shared';

/**
 * REPORT-002 — derive the single lifecycle state every surface (chat tools,
 * catalog, detail page) reports for a persisted document:
 *
 *  - `needs-review` — a retained draft the design/quality gate withheld; it is
 *    owner-visible but NEVER publicly shareable, even if a stale `shared` flag
 *    is still set (the share page fails closed the same way);
 *  - `private`      — a published report without a public link (`/reports/{id}`
 *    is the only valid URL for it);
 *  - `shared`       — explicit persisted `shared === true` on a published
 *    report; only in this state may `/share/report/{id}` be emitted.
 */
export function reportLifecycleState(doc: { reviewStatus?: unknown; shared?: unknown }): ReportLifecycleState {
  if (!isPublishedReport(doc.reviewStatus)) return 'needs-review';
  return doc.shared === true ? 'shared' : 'private';
}

// ============================================================================
// METADATA SCHEMA
// ============================================================================

/**
 * Report metadata schema.
 * Contains descriptive info and the data snapshot timestamp.
 */
export const reportMetadataSchema = z.object({
  /** Short description for link previews and listings */
  description: z.string().min(1, 'Description is required'),
  /** Optional Open Graph image URL for link previews */
  ogImage: z.string().url().optional(),
  /** ISO timestamp of when graph data was captured for the report */
  dataSnapshotAt: z.string().min(1, 'Data snapshot timestamp is required'),
});

export type ReportMetadata = z.infer<typeof reportMetadataSchema>;

// ============================================================================
// CREATE REPORT SCHEMA
// ============================================================================

/**
 * Schema for creating a new Report.
 * Used for validating input at the API boundary.
 */
export const createReportSchema = z
  .object({
    /**
     * Report title (displayed in listings and page header). Decoded on write
     * — titles occasionally arrive HTML-entity-encoded (e.g. an agent
     * copying its title out of the report's own <title> tag), which would
     * otherwise render literally as "&amp;" since titles are plain text, not
     * HTML (see ReportsTable.tsx / decode-html-entities.ts).
     */
    title: z
      .string()
      .min(1, 'Title is required')
      .max(200, 'Title must be 200 characters or fewer')
      .transform(decodeHtmlEntities),
    /** Self-contained HTML+CSS content */
    html: z.string().min(1, 'HTML content is required'),
    /** Who created this report (actor type) */
    createdBy: z.enum(['agent', 'user']),
    /**
     * Owning user UID — required for per-user authorization (C4).
     * Mission-driven publishes set this to mission.userId; user-driven
     * creates set it to the authenticated caller's UID. Optional in the
     * schema for backward compat; pre-2026-05-05 reports may lack it.
     */
    ownerId: z.string().min(1).optional(),
    /** Agent type if created by an agent */
    agentType: z.string().optional(),
    /** Mission ID that triggered report generation */
    missionId: z.string().optional(),
    /** Entity IDs referenced in the report */
    entityIds: z.array(z.string()).default([]),
    /** Report metadata */
    metadata: reportMetadataSchema,
    /** Whether this report has a public share link */
    shared: z.boolean().default(false),
  })
  // H3: writer-side enforcement. Agent-authored reports always come from a
  // mission orchestrator turn (publishReport requires context.missionId at
  // runtime) so the schema must mirror that — otherwise any future writer
  // that bypasses the report-tools layer could create headless agent rows.
  // User-authored reports remain unconstrained: a human can publish ad-hoc.
  .refine((r) => r.createdBy !== 'agent' || !!r.missionId, {
    message: 'missionId is required when createdBy is "agent"',
    path: ['missionId'],
  });

export type CreateReportInput = z.infer<typeof createReportSchema>;

// ============================================================================
// FULL REPORT SCHEMA
// ============================================================================

/**
 * REPORT-002 — the persisted quality-gate receipt behind a needs-review draft:
 * the final verdict, the exact failed checks, and the bounded repair guidance
 * shown to the owner. One record per report head; superseded on re-evaluation.
 */
export const reportQualityGateSchema = z.object({
  /** Final L1 verdict for the persisted head html. */
  verdict: z.enum(['PASS', 'REVISE', 'FAIL']),
  /** ISO timestamp of the evaluation that produced this receipt. */
  evaluatedAt: z.string(),
  /** The exact checks that failed (name + human detail + criticality). */
  failingChecks: z.array(
    z.object({
      name: z.string(),
      detail: z.string(),
      critical: z.boolean(),
    })
  ),
  /** Bounded owner repair path (review / edit / restore / approve guidance). */
  repair: z.string(),
});
export type ReportQualityGate = z.infer<typeof reportQualityGateSchema>;

/**
 * Full Report schema as stored in Firestore.
 * Includes auto-generated fields (id, createdAt).
 */
export const reportSchema = z.object({
  /** Unique report identifier */
  id: z.string().min(1),
  /** Report title */
  title: z.string().min(1).max(200),
  /** Self-contained HTML+CSS content */
  html: z.string().min(1),
  /** ISO timestamp of creation */
  createdAt: z.string(),
  /** Who created this report (actor type) */
  createdBy: z.enum(['agent', 'user']),
  /** Owning user UID — see createReportSchema for semantics. */
  ownerId: z.string().min(1).optional(),
  /** Agent type if created by an agent */
  agentType: z.string().optional(),
  /** Mission ID that triggered report generation */
  missionId: z.string().optional(),
  /** Entity IDs referenced in the report */
  entityIds: z.array(z.string()),
  /** Report metadata */
  metadata: reportMetadataSchema,
  /** Whether this report has a public share link */
  shared: z.boolean(),
  /** ISO timestamp of last update (set when report is edited) */
  updatedAt: z.string().optional(),
  /**
   * REPORT-001 design-review lifecycle. `published` is a final catalog/share
   * artifact; `needs-review` is a retained draft whose design review did not
   * pass (or could not be run) and is therefore withheld from the catalog and
   * public share surface. Absent → treated as `published` (every pre-REPORT-001
   * report, and any report published without a design brief).
   */
  reviewStatus: z.enum(['published', 'needs-review']).optional(),
  /** The design review's verdict for the CURRENT html: PASS / FAIL, or UNREVIEWED when the analyzer errored. */
  designPassVerdict: z.enum(['PASS', 'FAIL', 'UNREVIEWED']).optional(),
  /** Human-readable design-review findings behind a FAIL/UNREVIEWED verdict. */
  designPassDetails: z.string().optional(),
  /** Identity of the exact self-contained export reviewed before publication. */
  artifactIdentity: z
    .object({
      sha256: z.string().regex(/^[a-f0-9]{64}$/),
      cssSha256: z.string().regex(/^[a-f0-9]{64}$/),
      bytes: z.number().int().positive(),
      stagedAt: z.string(),
      revisionNumber: z.number().int().nonnegative(),
      reviewedBy: z.tuple([z.literal('design-pass'), z.literal('critique-report')]),
      evidenceBundleSha256: z.string().regex(/^[a-f0-9]{64}$/),
    })
    .nullable()
    .optional(),
  /**
   * REPORT-002: the exact quality-gate outcome that retained this report as a
   * needs-review draft — the owner-facing "why is this withheld and how do I
   * repair it" record. Written by the mission finalizer when the post-revision
   * verdict is not PASS; cleared (null) when a later evaluation passes or the
   * owner approves. Absent on reports that never went through a mission gate.
   */
  qualityGate: reportQualityGateSchema.nullable().optional(),
});

export type Report = z.infer<typeof reportSchema>;

// ============================================================================
// UPDATE REPORT SCHEMA
// ============================================================================

/**
 * Schema for updating an existing Report.
 * All fields are optional — only provided fields are updated.
 */
export const updateReportSchema = z.object({
  /** Updated title — decoded on write, see createReportSchema's title field */
  title: z
    .string()
    .min(1, 'Title is required')
    .max(200, 'Title must be 200 characters or fewer')
    .transform(decodeHtmlEntities)
    .optional(),
  /** Updated HTML content */
  html: z.string().min(1, 'HTML content is required').optional(),
  /** Toggle public share link */
  shared: z.boolean().optional(),
  /** Updated metadata (partial) */
  metadata: reportMetadataSchema.partial().optional(),
  /** REPORT-001: restore/override the design-review lifecycle status. */
  reviewStatus: z.enum(['published', 'needs-review']).optional(),
  /** REPORT-001: restore/override the design-review verdict. */
  designPassVerdict: z.enum(['PASS', 'FAIL', 'UNREVIEWED']).optional(),
  /** REPORT-001: restore/override the design-review findings. */
  designPassDetails: z.string().optional(),
  /** REPORT-002: set/clear the quality-gate receipt (null clears it). */
  qualityGate: reportQualityGateSchema.nullable().optional(),
});

export type UpdateReportInput = z.infer<typeof updateReportSchema>;

// ============================================================================
// REPORT VERSION SCHEMA (DISC-014)
// ============================================================================

/**
 * A superseded report version, stored one-per-doc in the
 * `reports/{id}/versions/{versionId}` subcollection.
 *
 * A version is captured whenever a report's html is replaced (edit, mission
 * revision, recommendation execution, or restore). History is monotonic and
 * append-only: nothing is ever overwritten or deleted, so a report can always
 * be restored to any earlier point in time.
 */
export const reportVersionSchema = z.object({
  /** Monotonic version number (1-based), unique and increasing within a report. */
  versionNumber: z.number().int().positive(),
  /** The full html body of this version. */
  html: z.string(),
  /** Byte length of `html` — lets the history list show size without loading bodies. */
  htmlLength: z.number().int().nonnegative(),
  /** ISO timestamp when this version was captured into history. */
  createdAt: z.string(),
  /**
   * Actor whose save captured this version into history, e.g. `user:<uid>`,
   * `agent:creator`, `agent:artifact-recommender`. `unknown` when unattributable
   * (a folded legacy `previousHtml` predating version tracking).
   */
  savedBy: z.string(),
  /** Why the version was captured, e.g. `revision`, `restore`, `pre-revision`, `legacy-previous`. */
  reason: z.string().optional(),
  /**
   * REPORT-004: sha256 of the exact `html`, stamped on pre-revision captures so
   * a revision reference (and its rollback) can be verified byte-for-byte.
   */
  htmlSha256: z.string().optional(),
  /**
   * REPORT-004: the quality/design evidence frozen with a pre-revision capture
   * — the verdict, failing check names, and design lifecycle the head carried
   * when the paid revision was dispatched.
   */
  checkReceipt: z
    .object({
      verdict: z.enum(['PASS', 'REVISE', 'FAIL']).optional(),
      failingChecks: z.array(z.string()).optional(),
      designPassVerdict: z.enum(['PASS', 'FAIL', 'UNREVIEWED']).optional(),
      reviewStatus: z.enum(['published', 'needs-review']).optional(),
      designPassDetails: z.string().optional(),
    })
    .optional(),
});
export type ReportVersionRecord = z.infer<typeof reportVersionSchema>;

/** Metadata-only version projection — everything except the (heavy) html body. */
export const reportVersionSummarySchema = reportVersionSchema.omit({ html: true });
export type ReportVersionSummaryRecord = z.infer<typeof reportVersionSummarySchema>;

/** A stored report version with its Firestore doc id. */
export type ReportVersion = ReportVersionRecord & { versionId: string };
/** A version's list-projection (no html body) with its Firestore doc id. */
export type ReportVersionSummary = ReportVersionSummaryRecord & { versionId: string };
