'use client';

/**
 * @file components/ai/AIDisclosureBadge.tsx
 * @description Unified AI-disclosure component with three responsive variants,
 * giving Radarist a single, consistent, review-first transparency surface.
 *
 * Variants:
 * - inline-badge: per-item Sparkles marker for rows / cards / visualizations
 * - page-disclaimer: page-level disclosure paragraph + link to LIMITATIONS
 * - report-footer: visible footer disclaimer for rendered reports
 *
 * The canonical copy lives here so every surface says the same thing.
 * @created 2026-06-06
 */

import React from 'react';
import { Sparkles } from 'lucide-react';

import { Badge } from '@/components/ui/badge';
import { Tooltip, TooltipContent, TooltipProvider, TooltipTrigger } from '@/components/ui/tooltip';
import { PUBLIC_LIMITATIONS_URL } from '@/lib/public-documentation';
import { cn } from '@/lib/utils';

export interface AIDisclosureBadgeProps {
  variant: 'inline-badge' | 'page-disclaimer' | 'report-footer';
  /** Optional confidence %, rendered only on the inline-badge variant. */
  confidence?: number;
  className?: string;
}

export const AIDisclosureBadge = React.memo(function AIDisclosureBadge({
  variant,
  confidence,
  className,
}: AIDisclosureBadgeProps) {
  if (variant === 'inline-badge') {
    return (
      <TooltipProvider>
        <Tooltip>
          <TooltipTrigger asChild>
            <Badge
              variant="outline"
              aria-label="AI-generated content"
              data-testid="ai-disclosure-badge"
              className={cn(
                'shrink-0 gap-1 bg-purple-100 text-purple-700 border-purple-300 dark:bg-purple-900 dark:text-purple-300 dark:border-purple-700',
                className
              )}
            >
              <Sparkles className="h-3 w-3" />
              AI-Generated
              {confidence !== undefined && ` (${confidence}%)`}
            </Badge>
          </TooltipTrigger>
          <TooltipContent>
            <p className="text-xs">This content was generated by AI. Review it for accuracy.</p>
          </TooltipContent>
        </Tooltip>
      </TooltipProvider>
    );
  }

  if (variant === 'page-disclaimer') {
    return (
      <div
        role="note"
        aria-label="AI-assisted content notice"
        data-testid="ai-disclosure-page"
        className={cn(
          'rounded-lg border border-blue-200 bg-blue-50 p-4 text-sm text-blue-900 dark:border-blue-800 dark:bg-blue-950/20 dark:text-blue-200',
          className
        )}
      >
        <p className="flex items-start gap-2">
          <Sparkles className="mt-0.5 h-4 w-4 shrink-0 text-blue-600 dark:text-blue-400" />
          <span>
            <strong>AI-Assisted Content:</strong> This page contains AI-generated or AI-assisted information. Please
            review it for accuracy and relevance. See our{' '}
            <a
              href={PUBLIC_LIMITATIONS_URL}
              target="_blank"
              rel="noopener noreferrer"
              className="underline hover:no-underline"
            >
              limitations
            </a>{' '}
            for details.
          </span>
        </p>
      </div>
    );
  }

  // report-footer
  return (
    <div
      data-testid="ai-disclosure-footer"
      className={cn('report-footer flex flex-col items-center gap-3 border-t border-border py-6', className)}
    >
      <p className="footer-disclaimer flex items-center gap-2 text-xs text-muted-foreground">
        <Sparkles className="h-3.5 w-3.5 shrink-0" />
        This report was generated with AI assistance. Please review it for accuracy. Generated by Radarist Studio.
      </p>
    </div>
  );
});

AIDisclosureBadge.displayName = 'AIDisclosureBadge';
