/**
 * @file scripts/build-report-fonts.ts
 * @description Embed the report brand type pair
 * (Inter 400/600/800, Playfair Display 700/800; OFL-licensed, latin subset)
 * directly into `public/css/report-brand.css` as data-URI `@font-face` rules.
 *
 * Why: the report viewer renders reports inside an opaque-origin iframe with a
 * deny-by-default CSP (`font-src data:` only) and strips `<link>`/`@import` —
 * so no network font can load there. Embedding as data: URIs is the path that
 * renders the mandated type pair for every report, old and new.
 *
 * Idempotent: writes between the FONTS:BEGIN / FONTS:END markers, replacing any
 * previous block. Refuses to write if the generated block exceeds MAX_BYTES.
 *
 * Run: npx tsx scripts/build-report-fonts.ts
 */
import * as fs from 'node:fs';
import * as path from 'node:path';

const CSS_PATH = path.resolve(__dirname, '../public/css/report-brand.css');
const BEGIN = '/* FONTS:BEGIN (generated by scripts/build-report-fonts.ts — do not hand-edit) */';
const END = '/* FONTS:END */';
const MAX_BYTES = 400_000;

const FAMILIES = [
  { family: 'Inter', weights: [400, 600, 800] },
  { family: 'Playfair Display', weights: [700, 800] },
];

// A modern-browser UA so the Google Fonts CSS2 endpoint serves woff2 sources.
const UA =
  'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0 Safari/537.36';

interface Face {
  family: string;
  weight: number;
  dataUri: string;
}

async function fetchLatinFace(family: string, weight: number): Promise<Face> {
  const cssUrl = `https://fonts.googleapis.com/css2?family=${encodeURIComponent(family)}:wght@${weight}&display=swap`;
  const cssRes = await fetch(cssUrl, { headers: { 'User-Agent': UA } });
  if (!cssRes.ok) throw new Error(`fonts css fetch failed ${cssRes.status} for ${family} ${weight}`);
  const css = await cssRes.text();
  // The CSS2 response contains one @font-face per subset, each preceded by a
  // `/* latin */`-style comment. Take the block labeled exactly `latin`.
  const blocks = css.split('@font-face').slice(1);
  let woff2Url: string | undefined;
  for (let i = 0; i < blocks.length; i++) {
    const precedingComment = css.slice(0, css.indexOf('@font-face' + blocks[i])).match(/\/\*\s*([a-z-]+)\s*\*\/\s*$/);
    const label = precedingComment?.[1];
    if (label === 'latin') {
      woff2Url = blocks[i].match(/url\((https:[^)]+\.woff2)\)/)?.[1];
      break;
    }
  }
  // Fallback: last block (Google orders latin last).
  if (!woff2Url) woff2Url = blocks[blocks.length - 1]?.match(/url\((https:[^)]+\.woff2)\)/)?.[1];
  if (!woff2Url) throw new Error(`no woff2 url found for ${family} ${weight}`);
  const fontRes = await fetch(woff2Url, { headers: { 'User-Agent': UA } });
  if (!fontRes.ok) throw new Error(`woff2 fetch failed ${fontRes.status} for ${family} ${weight}`);
  const buf = Buffer.from(await fontRes.arrayBuffer());
  return { family, weight, dataUri: `data:font/woff2;base64,${buf.toString('base64')}` };
}

async function main(): Promise<void> {
  const faces: Face[] = [];
  for (const { family, weights } of FAMILIES) {
    for (const weight of weights) {
      const face = await fetchLatinFace(family, weight);
      // eslint-disable-next-line no-console -- build script progress
      console.log(`fetched ${family} ${weight}: ${Math.round(face.dataUri.length / 1024)} KB (base64)`);
      faces.push(face);
    }
  }

  const block = [
    BEGIN,
    '/* Inter & Playfair Display — SIL Open Font License 1.1 (https://openfontlicense.org).',
    ' * Latin subsets, embedded as data: URIs because the report viewer CSP only',
    ' * allows font-src data: (see src/lib/reports/static-report-html.ts). */',
    ...faces.map((f) =>
      [
        '@font-face {',
        `  font-family: '${f.family}';`,
        '  font-style: normal;',
        `  font-weight: ${f.weight};`,
        '  font-display: swap;',
        `  src: url(${f.dataUri}) format('woff2');`,
        '}',
      ].join('\n')
    ),
    END,
  ].join('\n');

  if (Buffer.byteLength(block) > MAX_BYTES) {
    throw new Error(`generated font block is ${Buffer.byteLength(block)} bytes (> ${MAX_BYTES}) — refusing to write`);
  }

  let css = fs.readFileSync(CSS_PATH, 'utf-8');
  const beginIdx = css.indexOf(BEGIN);
  if (beginIdx !== -1) {
    const endIdx = css.indexOf(END, beginIdx);
    if (endIdx === -1) throw new Error('FONTS:BEGIN without FONTS:END — refusing to write');
    css = css.slice(0, beginIdx) + block + css.slice(endIdx + END.length);
  } else {
    css = `${block}\n${css}`;
  }
  fs.writeFileSync(CSS_PATH, css);
  // eslint-disable-next-line no-console -- build script result
  console.log(
    `wrote ${faces.length} font faces into ${CSS_PATH} (${Math.round(Buffer.byteLength(block) / 1024)} KB block)`
  );
}

main().catch((err) => {
  // eslint-disable-next-line no-console -- build script failure
  console.error(err);
  process.exit(1);
});
