/**
 * @file ai/image-client.ts
 * @description Gemini image generation client using Nano Banana models.
 *
 * Used by:
 * - Creator agent (generateInfographic for reports, pathPrefix='infographics')
 * - AI Assistant (generateVisualization tool, pathPrefix='visualizations')
 *
 * Server-only module — do NOT import in 'use client' components.
 *
 * @phase Impulse v1.0 — Phase 1: Nano Banana Integration
 */

import { GoogleGenerativeAI } from '@google/generative-ai';
import { uploadImage } from '@/lib/storage';
import { resolveGeminiApiKey, MissingAIKeyError } from './key-resolution';
import { geminiImageModel } from './model-config';
import { buildInfographicPrompt } from './infographic-prompt';
import { createLogger } from '@/lib/logger';
import { validateRasterImageContainer } from '@/lib/raster-image';
import { captureProviderUsage } from '@/lib/operation-context';
import { geminiUsageToReceipt, type GeminiUsageMetadataLike } from '@/lib/operation-usage-map';
import type { OperationUsageCompleteness } from '@/lib/schemas/operation-receipt';

const log = createLogger('ai/image-client');

// Gemini image generation models — env-backed via geminiImageModel()
// (default: gemini-3-pro-image = Nano Banana Pro, highest quality).
// Both tiers resolve to the same configured model — we use the best model for
// all paths; the 'fast'/'quality' selector is kept for call-site compatibility.
const MODELS = {
  fast: geminiImageModel(), // Nano Banana Pro — use the best model for all paths
  quality: geminiImageModel(), // Nano Banana Pro (highest quality)
} as const;

export interface InfographicRequest {
  prompt: string;
  style?: 'professional' | 'minimal' | 'colorful' | 'dark';
  model?: 'fast' | 'quality';
  aspectRatio?: '1:1' | '16:9' | '4:3' | '9:16';
  userId: string;
  pathPrefix?: string; // 'infographics' (default) or 'visualizations'
  filename?: string; // Optional custom filename
  /** Brand palette/style fragment (from the mission DesignBrief) — when set, the
   *  generated image matches the report's brand instead of a generic palette. */
  brandStyle?: string;
  /** Optional reference image (base64, no data: prefix) used as a visual template
   *  for layout/palette/typography. Text-only callers are unaffected. */
  referenceImage?: { data: string; mimeType: string };
}

export interface InfographicResult {
  success: boolean;
  url: string | null;
  error?: string;
  mimeType?: string;
  /** Decoded image dimensions when the generated PNG/JPEG stream is structurally valid. */
  width?: number;
  height?: number;
  /** Exact number of generated bytes uploaded to Storage. */
  sizeBytes?: number;
  /** True when an image was generated by AI — drives the AI-Generated disclosure badge (EU AI Act Art 50). */
  aiGeneratedBadge?: boolean;
  /** Provenance attached to AI-generated images (Art 50(2) machine-readable marking). */
  provenance?: {
    provider: string;
    model: string;
    timestamp: string;
    /** Whether any upstream SynthID watermark was left intact (we never re-encode the bytes). */
    synthIdPreserved: boolean;
  };
}

export async function generateInfographic(request: InfographicRequest): Promise<InfographicResult> {
  const {
    prompt,
    style = 'professional',
    model = 'fast',
    aspectRatio = '16:9',
    userId,
    pathPrefix = 'infographics',
    filename,
    brandStyle,
    referenceImage,
  } = request;

  try {
    // Centralized key resolution (GOOGLE_API_KEY or GEMINI_API_KEY; setup-script
    // placeholders count as missing) — see src/lib/ai/client.ts.
    const apiKey = resolveGeminiApiKey();
    if (!apiKey) throw new MissingAIKeyError();

    const genAI = new GoogleGenerativeAI(apiKey);
    const genModel = genAI.getGenerativeModel({
      model: MODELS[model],
      generationConfig: {
        // @ts-expect-error -- responseModalities is valid for image-capable models
        responseModalities: ['IMAGE', 'TEXT'],
      },
    });

    const fullPrompt = buildInfographicPrompt({ prompt, style, aspectRatio, brandStyle });

    log.info('[image] Generating infographic', {
      model: MODELS[model],
      style,
      aspectRatio,
    });

    const genContent = referenceImage
      ? [{ inlineData: { mimeType: referenceImage.mimeType, data: referenceImage.data } }, { text: fullPrompt }]
      : fullPrompt;
    const result = await genModel.generateContent(genContent);
    const candidate = result.response.candidates?.[0];
    const imagePart = candidate?.content?.parts?.find((p: { inlineData?: { mimeType: string } }) =>
      p.inlineData?.mimeType?.startsWith('image/')
    );

    // ARUN-022 — capture the image provider response into the ambient sink
    // (no-op without a boundary). One produced image → imageCount 1; any reported
    // token usage is mapped through the shared Gemini mapper. Completeness is
    // honest: `complete` when the provider reported token usage, `partial` when we
    // know only that one image was produced, `unreported` when neither is known.
    // Structurally non-fatal: guarded so a capture edge case never fails image gen.
    const imageProduced = Boolean(imagePart?.inlineData);
    try {
      const imageUsageMetadata = (result.response as { usageMetadata?: GeminiUsageMetadataLike }).usageMetadata;
      const mappedImageUsage = geminiUsageToReceipt(imageUsageMetadata);
      const imageCompleteness: OperationUsageCompleteness = imageUsageMetadata
        ? 'complete'
        : imageProduced
          ? 'partial'
          : 'unreported';
      captureProviderUsage({
        provider: 'gemini',
        operation: 'gemini.generate-infographic',
        requestedModel: MODELS[model],
        providerModel: (result.response as { modelVersion?: unknown }).modelVersion,
        counters: { ...mappedImageUsage.counters, ...(imageProduced ? { imageCount: 1 } : {}) },
        usageCompleteness: imageCompleteness,
        // Image generation is token-billed here; no separate provider fee applies.
        occurredAt: new Date().toISOString(),
        feeState: 'none',
      });
    } catch (captureError) {
      log.warn('[image] operation-usage capture skipped (non-fatal)', {
        error: captureError instanceof Error ? captureError.message : String(captureError),
      });
    }

    if (!imagePart?.inlineData) {
      log.warn('[image] No image in Gemini response');
      return { success: false, url: null, error: 'No image generated' };
    }

    const imageBuffer = Buffer.from(imagePart.inlineData.data, 'base64');
    const dimensions = validateRasterImageContainer(imageBuffer, imagePart.inlineData.mimeType);
    if (!dimensions) {
      throw new Error('Generated image is not a structurally valid, bounded PNG or JPEG container.');
    }
    // We upload the Gemini bytes verbatim (no transcode), so any upstream SynthID
    // watermark Gemini embeds survives intact. We attach our own provenance record
    // for the Art 50(2) machine-readable marking; a C2PA manifest is a documented
    // fast-follow (see docs/RESPONSIBLE-AI.md §10).
    const url = await uploadImage(imageBuffer, userId, imagePart.inlineData.mimeType, pathPrefix, filename);

    const provenance = {
      provider: 'Radarist Studio',
      model: MODELS[model],
      timestamp: new Date().toISOString(),
      synthIdPreserved: true,
    };

    log.info('[image] Infographic uploaded', { url, provenance });
    return {
      success: true,
      url,
      mimeType: imagePart.inlineData.mimeType,
      ...(dimensions ?? {}),
      sizeBytes: imageBuffer.length,
      aiGeneratedBadge: true,
      provenance,
    };
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    log.error('[image] Generation failed', error instanceof Error ? error : new Error(message));
    return { success: false, url: null, error: message };
  }
}
