// ============================================================================
// RADAR TYPES
// ============================================================================
// Radar visualization, entries, placements, quadrants, rings, and
// technology decoupling types.

import type { DeepResearchData, TechnologyResearch } from './research';

/**
 * Default quadrants for the tech radar.
 * Typically divides the radar into Techniques, Tools, Platforms, and Languages & Frameworks.
 */
export const QUADRANTS = ['Techniques', 'Tools', 'Platforms', 'Languages & Frameworks'] as const;

/**
 * Available statuses for a technology.
 * Used to indicate the current trend or condition of the technology (e.g., Rising, Stable).
 */
export const STATUSES = ['Trending', 'Stable', 'Fading', 'New', 'Warning'] as const;

/**
 * Type representing a Quadrant. Can be one of the default quadrants or a custom string.
 */
export type Quadrant = (typeof QUADRANTS)[number] | string;

/**
 * Type representing a Ring. Can be any string to support dynamic ring systems.
 */
export type Ring = string; // Allow dynamic rings

/**
 * Type representing the status of a radar entry.
 */
export type Status = (typeof STATUSES)[number];

/**
 * Supported ring systems for categorization.
 * - Standard: Adopt, Trial, Assess, Hold (HATA model)
 * - TRL: Technology Readiness Levels 1-9
 * - Time-to-Impact: Horizon-based H1, H2, H3
 * @phase Phase 2 Task 2.3.2
 */
export type RingSystem = 'Standard' | 'TRL' | 'Time-to-Impact';

/**
 * Base interface for a technology item.
 */
export interface RadarTechnology {
  /** The name of the technology. */
  name: string;
  /** A description of the technology. */
  description: string;
}

/**
 * Represents a historical record of a radar entry's movement or state change.
 */
export interface RadarEntryHistory {
  /** The date of the record (ISO string or YYYY-MM-DD). */
  date: string;
  /** The ring the entry was in at that time. */
  ring: Ring;
  /** The status of the entry at that time. */
  status: Status;
}

/**
 * Represents a specific entry on the radar.
 * Extends `RadarTechnology` with position, categorization, and metadata.
 */
export interface RadarEntry extends RadarTechnology {
  /**
   * The decoupled model's REAL Technology doc id (AUDIT-010). The legacy
   * numeric `id` is a display hash; consumers that write provenance
   * (signal `importedAs`) must use this instead — it is what the
   * Firestore lookups and the Neo4j BECAME sync match on.
   */
  technologyId?: string;
  /** Unique numeric ID for the entry. */
  id: number;
  /**
   * Stable id of the quadrant this entry belongs to.
   * References `RadarData.quadrants[].id` on the parent radar.
   */
  quadrantId: string;
  /**
   * **Read-only denormalized display name.**
   *
   * Populated by the service/adapter layer when entries are loaded; never
   * written directly to Firestore. The Zod `createRadarPlacementInputSchema`
   * deliberately omits this field so write APIs cannot persist a stale name.
   *
   * Consumers that need a guaranteed non-optional name should use
   * `RadarEntryView` (which makes this field required) — this field is
   * marked optional on the stored type so every caller reading from Firestore
   * sees it as `string | undefined` and can fall back to `quadrantId`.
   */
  quadrantName?: string;
  /**
   * Indicator of movement since the last update.
   * 0 = no change, 1 = moved inward/up, -1 = moved outward/down.
   */
  moved?: number;
  /** Manual X position override (0-100 scale). */
  x?: number;
  /** Manual Y position override (0-100 scale). */
  y?: number;
  /** The current ring assignment. */
  ring: Ring;
  /** Optional specific TRL level (e.g., "TRL 1"). */
  trl?: string;
  /** Optional Standard/HATA value (e.g., "Assess"). */
  hata?: string;
  /**
   * Time-to-Impact horizon for this entry.
   * Format: "H1 (0-6mo)", "H2 (6-18mo)", "H3 (18+mo)"
   * @phase Phase 2 Task 2.3.1
   */
  timeToImpact?: string;
  /** List of tags for categorization and filtering. */
  tags: string[];
  /** Detailed analysis or notes generated by AI or user. */
  analysis?: string;
  /** Current status trend. */
  status: Status;
  /** Estimated cost or effort to prototype (0-100 scale). */
  costToPrototype: number;
  /** Alignment with strategic goals. */
  strategyAlignment?: 'aligned' | 'conflict' | 'neutral' | string;
  /** Historical data for this entry. */
  history?: RadarEntryHistory[];
  /** Linked company IDs (vendors/partners using this technology). */
  linkedCompanies?: string[];
  /** Linked use case IDs (business applications for this technology). */
  linkedUseCases?: string[];
  /** Deep research data (from Technology entity during migration). */
  deepResearch?: DeepResearchData;
  /**
   * Comprehensive research data (new model - preferred over deepResearch).
   * @tech-debt This duplicates research data. Future work should consolidate
   * deepResearch and comprehensiveResearch into a single field.
   */
  comprehensiveResearch?: TechnologyResearch;
  /** Original technology ID (UUID) for reverse lookup during migration. */
  originalTechId?: string;
}

/**
 * Form-to-service contract for creating or editing a radar entry.
 *
 * `technologyId` is authoritative when the user selected an existing
 * Technology. Save handlers must not fall back to a name or slug after that
 * ID fails to resolve, because doing so can create a duplicate Technology.
 */
export type RadarEntrySaveInput = Omit<RadarEntry, 'id' | 'analysis' | 'history'> & {
  id?: number;
};

/** Explicit outcome used by create/rename dialogs before they may close. */
export type RadarManagementResult = { ok: true } | { ok: false; error: string };

/**
 * Configuration for a single quadrant in a radar.
 * Allows custom naming and descriptions for each quadrant.
 * @phase Phase 2 Task 2.1.3
 */
export interface QuadrantConfig {
  /** Unique identifier for the quadrant. */
  id: string;
  /** Display name (e.g., "AI & ML" instead of "Techniques"). */
  name: string;
  /** Optional description of what belongs in this quadrant. */
  description?: string;
  /** Position order (0-3) for quadrant placement. */
  order: number;
}

/**
 * Configuration for a single ring in a radar.
 * Supports custom ring configurations beyond standard HATA.
 * @phase Phase 2 Task 2.1.3
 */
export interface RingConfig {
  /** Unique identifier for the ring. */
  id: string;
  /** Display name (e.g., "Adopt", "TRL 1", "H1"). */
  name: string;
  /** Optional description of the ring criteria. */
  description?: string;
  /** Position order (0 = innermost, higher = outer). */
  order: number;
  /** Optional color for this ring in visualizations. */
  color?: string;
}

/**
 * Represents the entire state of a Radar instance.
 * Supports dynamic quadrant and ring configurations.
 * @phase Phase 2 Task 2.1.3 - Updated for dynamic quadrants/rings
 */
export interface RadarData {
  /** Unique string ID for the radar. */
  id: string;
  /** Display name of the radar. */
  name: string;
  /** URL-friendly slug for the radar. */
  slug?: string;
  /** Optional description of the radar's purpose. */
  description?: string;

  /**
   * Canonical list of quadrants on this radar.
   *
   * Always `QuadrantConfig[]` post-migration. Length is bounded to
   * `MIN_QUADRANTS..MAX_QUADRANTS` (1..8) by the service layer. Each entry
   * has a stable `id` that placements/entries reference via `quadrantId`.
   *
   * Pre-migration radar docs may still carry `string[]` here — use
   * `resolveQuadrantConfigs(radar)` on every read surface during the
   * transition window.
   */
  quadrants: QuadrantConfig[];

  /**
   * Optional ring configuration.
   * When not provided, defaults to the ring system's standard rings.
   */
  ringConfigs?: RingConfig[];

  /** List of entries on the radar. */
  entries: RadarEntry[];

  /** The ring system configuration used (e.g., "Standard" or "TRL"). */
  ringSystem?: RingSystem; // Optional for backward compatibility, defaults to Standard

  /**
   * Public-link opt-in (AUDIT-001). `/share/{radarId}` renders ONLY when this
   * is exactly `true` — absent/false fails closed, matching the report and
   * visualization share gates. Toggled from ShareDialog; never set at create.
   */
  shared?: boolean;

  /** When the radar was created (Unix timestamp). */
  createdAt?: number;
  /** When the radar was last updated (Unix timestamp). */
  updatedAt?: number;
  /** User ID of who created this radar. */
  createdBy?: string;
}

// ============================================================================
// TECHNOLOGY DECOUPLING TYPES (Phase 1)
// ============================================================================
// These types separate facts (Technology) from opinions (RadarPlacement)
// to enable multi-radar support where the same technology can be placed
// on different radars with different positions.

/**
 * Time-to-Impact horizon type for radar placements.
 * Uses "horizon" terminology common in innovation management:
 * - H1: Near-term (0-1 year) - Immediate impact, ready for adoption
 * - H2: Medium-term (1-3 years) - Emerging, requires investment
 * - H3: Long-term (3+ years) - Exploratory, future potential
 * - unknown: Not yet assessed
 *
 * @phase Phase 0 Task 0.2.2
 */
export type TimeToImpact = 'H1' | 'H2' | 'H3' | 'unknown';

/**
 * Denormalized snapshot of Technology data stored in RadarPlacement.
 * Used for performance optimization to avoid N+1 queries.
 * @phase Phase 2 Task 2.1.1
 */
export interface TechnologySnapshot {
  /** Technology name for display. */
  name: string;
  /** Technology slug for URL generation. */
  slug: string;
  /** Technology category for grouping. */
  category?: string;
  /** When the snapshot was last updated. */
  snapshotUpdatedAt?: number;
}

/**
 * Represents a Technology's position on a specific Radar.
 * This captures opinions (position, rationale) separate from facts.
 *
 * The same Technology can have multiple RadarPlacements on different radars.
 *
 * @example
 * ```typescript
 * const reactPlacement: RadarPlacement = {
 *   id: 'placement-789',
 *   technologyId: 'tech-123',
 *   radarId: 'radar-456',
 *   quadrant: 'languages-frameworks',
 *   ring: 'adopt',
 *   rationale: 'Mature, well-supported, team has expertise',
 *   x: 0.15,
 *   y: 0.25,
 *   createdAt: 1704067200000,
 *   updatedAt: 1704067200000,
 *   placedBy: 'user-456',
 * };
 * ```
 */
export interface RadarPlacement {
  /** Unique identifier for the placement. */
  id: string;
  /** Reference to the Technology being placed. */
  technologyId: string;
  /** Reference to the Radar this placement belongs to. */
  radarId: string;
  /**
   * Stable id of the quadrant this placement belongs to.
   * References `RadarData.quadrants[].id` on the parent radar.
   */
  quadrantId: string;
  /**
   * **Read-only denormalized display name.**
   *
   * Populated by the service/adapter layer on read; never written directly
   * to Firestore. The Zod `createRadarPlacementInputSchema` omits this field
   * so write APIs cannot persist a stale name. Use `RadarPlacementView` when
   * you need a guaranteed non-optional name.
   */
  quadrantName?: string;
  /** Which ring the technology is placed in (maturity/adoption level). */
  ring: Ring;
  /** Rationale for why this technology is placed here. */
  rationale?: string;
  /** Previous ring if moved (for tracking history). */
  movedFrom?: Ring;
  /** Timestamp when last moved between rings. */
  movedAt?: number;
  /** X coordinate for visualization (0-1). */
  x?: number;
  /** Y coordinate for visualization (0-1). */
  y?: number;
  /** Status of this placement. */
  status?: Status;
  /**
   * Time-to-Impact horizon for this placement.
   * Indicates when the technology is expected to have business impact.
   * Defaults to 'unknown' if not assessed.
   * @phase Phase 0 Task 0.2.2
   */
  timeToImpact?: TimeToImpact;
  /**
   * Technology Readiness Level score (1-9).
   * Alternative dimension to ring for maturity assessment.
   * @phase Phase 2 Task 2.1.1
   */
  trlScore?: number;
  /**
   * Denormalized snapshot of the technology for performance.
   * Avoids N+1 queries when rendering radar visualizations.
   * Updated when the source technology changes.
   * @phase Phase 2 Task 2.1.1
   */
  technologySnapshot?: TechnologySnapshot;
  /** Timestamp when created. */
  createdAt: number;
  /** Timestamp when last updated. */
  updatedAt: number;
  /** User ID who placed this on the radar. */
  placedBy: string;
}

/**
 * View / read shape for a `RadarPlacement`.
 *
 * Extends the stored `RadarPlacement` with a **required** `quadrantName`
 * denormalized at read time by the service/adapter layer. Every UI / display
 * component consumes `RadarPlacementView` — not the stored `RadarPlacement` —
 * so `quadrantName` is always present and no `?? '?'` fallback is required in
 * render paths.
 *
 * Keeping `quadrantName` off the stored `RadarPlacement` also keeps it out of
 * `CreateRadarPlacementInput` / `UpdateRadarPlacementInput` (they derive from
 * the stored type via `Omit`), so stale denormalized names can never be
 * accepted on a write path.
 */
export interface RadarPlacementView extends RadarPlacement {
  /** Display name of the quadrant, denormalized from the parent radar's config. */
  quadrantName: string;
}

/**
 * View / read shape for a `RadarEntry` (legacy sub-collection model).
 *
 * Same pattern as `RadarPlacementView`: UI components consume this View type
 * so the denormalized `quadrantName` is always present; the stored `RadarEntry`
 * stays lean and writes stay safe.
 */
export interface RadarEntryView extends RadarEntry {
  /** Display name of the quadrant, denormalized from the parent radar's config. */
  quadrantName: string;
}

/**
 * Input type for creating a new RadarPlacement.
 *
 * Explicitly omits `quadrantName` — it's a read-only denormalized display
 * field, never a write input. Callers cannot accidentally write a stale name.
 */
export type CreateRadarPlacementInput = Omit<RadarPlacement, 'id' | 'createdAt' | 'updatedAt' | 'quadrantName'>;

/**
 * Input type for updating an existing RadarPlacement.
 *
 * Excludes immutable fields (`id`, `technologyId`, `radarId`), audit fields
 * (`createdAt`, `updatedAt`), and the read-only denormalized `quadrantName`.
 */
export type UpdateRadarPlacementInput = Partial<
  Omit<RadarPlacement, 'id' | 'technologyId' | 'radarId' | 'createdAt' | 'updatedAt' | 'quadrantName'>
>;

// ============================================================================
// HELPER FUNCTIONS (Phase 2 Task 2.1.3)
// ============================================================================

/**
 * Type guard to check if quadrant is a QuadrantConfig object.
 * @phase Phase 2 Task 2.1.3
 */
export function isQuadrantConfig(quadrant: Quadrant | QuadrantConfig): quadrant is QuadrantConfig {
  return typeof quadrant === 'object' && quadrant !== null && 'id' in quadrant;
}

/**
 * Normalize quadrants to string array for backward compatibility.
 * Handles both legacy string arrays and new QuadrantConfig arrays.
 * @phase Phase 2 Task 2.1.3
 *
 * @example
 * ```typescript
 * // Legacy format
 * normalizeQuadrants(['Techniques', 'Tools', 'Platforms', 'Languages'])
 * // Returns: ['Techniques', 'Tools', 'Platforms', 'Languages']
 *
 * // New format
 * normalizeQuadrants([{ id: 'q1', name: 'AI & ML', order: 0 }, ...])
 * // Returns: ['AI & ML', ...]
 * ```
 */
export function normalizeQuadrants(quadrants: Quadrant[] | QuadrantConfig[]): string[] {
  if (!Array.isArray(quadrants)) return [];
  if (quadrants.length === 0) return [];

  // Check if first item is a QuadrantConfig
  if (isQuadrantConfig(quadrants[0])) {
    return (quadrants as QuadrantConfig[]).map((q) => q.name);
  }

  // Already a string array
  return quadrants as string[];
}

/**
 * Get quadrant name from a quadrant value (handles both string and QuadrantConfig).
 * @phase Phase 2 Task 2.1.3
 */
export function getQuadrantName(quadrant: Quadrant | QuadrantConfig): string {
  if (isQuadrantConfig(quadrant)) {
    return quadrant.name;
  }
  return quadrant;
}

// ============================================================================
// VARIABLE-QUADRANT HELPERS (1..8 per-radar quadrants)
// ============================================================================
// Added for the "Variable Quadrants" refactor. These are the single source of
// truth for looking up, validating, and reconciling per-radar quadrant configs.
// Existing helpers above (isQuadrantConfig, normalizeQuadrants, getQuadrantName)
// stay for backward compatibility during the transition window.

/**
 * Look up a single `QuadrantConfig` by stable id on a radar.
 *
 * Returns `undefined` if the id is not present or the radar's `quadrants` field
 * is still in the legacy `string[]` shape (in which case callers should route
 * through `resolveQuadrantConfigs` first).
 */
export function getQuadrantById(radar: Pick<RadarData, 'quadrants'>, quadrantId: string): QuadrantConfig | undefined {
  if (!Array.isArray(radar.quadrants)) return undefined;
  for (const q of radar.quadrants) {
    if (isQuadrantConfig(q) && q.id === quadrantId) {
      return q;
    }
  }
  return undefined;
}

/**
 * Case-insensitive lookup of a `QuadrantConfig` by display name on a radar.
 *
 * Compatibility helper for callers that intentionally accept surrounding
 * whitespace in legacy display names. External id-or-name references use
 * `resolveQuadrantReference`; update-quadrants merging remains ID-first via
 * `reconcileQuadrantConfigs`.
 */
export function findQuadrantByName(radar: Pick<RadarData, 'quadrants'>, name: string): QuadrantConfig | undefined {
  if (!Array.isArray(radar.quadrants) || !name) return undefined;
  const target = name.trim().toLowerCase();
  if (!target) return undefined;
  for (const q of radar.quadrants) {
    if (isQuadrantConfig(q) && q.name.trim().toLowerCase() === target) {
      return q;
    }
  }
  return undefined;
}

export type QuadrantReferenceMatch = 'id-or-name' | 'id' | 'name';
export type QuadrantReferencePrecedence = 'id-first' | 'name-first';

export interface ResolveQuadrantReferenceOptions {
  /** Restrict lookup to one side when a caller receives id and name in separate fields. */
  matchBy?: QuadrantReferenceMatch;
  /** Resolve the otherwise-valid cross-collision where one config's name equals another config's id. */
  precedence?: QuadrantReferencePrecedence;
}

/**
 * Resolve an external quadrant reference to its canonical config.
 *
 * Stable ids match exactly. Display names match case-insensitively but remain
 * whitespace-sensitive, preserving the existing AI tool contract. Callers
 * that intentionally accept trimmed legacy names should keep using
 * `findQuadrantByName`.
 */
export function resolveQuadrantReference(
  radar: Pick<RadarData, 'quadrants'>,
  reference: string,
  options: ResolveQuadrantReferenceOptions = {}
): Pick<QuadrantConfig, 'id' | 'name'> | undefined {
  if (!Array.isArray(radar.quadrants) || typeof reference !== 'string') return undefined;

  const matchBy = options.matchBy ?? 'id-or-name';
  const referenceName = reference.toLowerCase();
  let byId: Pick<QuadrantConfig, 'id' | 'name'> | undefined;
  let byName: Pick<QuadrantConfig, 'id' | 'name'> | undefined;

  for (const rawQuadrant of radar.quadrants as unknown[]) {
    if (!rawQuadrant || typeof rawQuadrant !== 'object') continue;

    const quadrant = rawQuadrant as Partial<QuadrantConfig>;
    if (typeof quadrant.id !== 'string' || quadrant.id.trim().length === 0) continue;
    if (typeof quadrant.name !== 'string' || quadrant.name.trim().length === 0) continue;

    if (!byId && matchBy !== 'name' && quadrant.id === reference) {
      byId = quadrant as Pick<QuadrantConfig, 'id' | 'name'>;
    }
    if (!byName && matchBy !== 'id' && quadrant.name.toLowerCase() === referenceName) {
      byName = quadrant as Pick<QuadrantConfig, 'id' | 'name'>;
    }
  }

  if (matchBy === 'id') return byId;
  if (matchBy === 'name') return byName;
  return options.precedence === 'name-first' ? (byName ?? byId) : (byId ?? byName);
}

/**
 * Convert a legacy `quadrants` value — which may be `string[]`, mixed, or
 * already `QuadrantConfig[]` — into a canonical `QuadrantConfig[]`.
 *
 * Used by the migration script and seed data only. Runtime code should already
 * see canonical `QuadrantConfig[]` post-migration.
 *
 * The `idGenerator` is pluggable so the migration script can use
 * `defaultQuadrantIdFromName` (deterministic, slug-based) while tests can use a
 * counter-based generator for stable snapshots.
 */
export function ensureQuadrantConfigs(
  legacy: readonly (string | QuadrantConfig)[] | undefined | null,
  idGenerator: (name: string, index: number) => string
): QuadrantConfig[] {
  if (!Array.isArray(legacy) || legacy.length === 0) return [];
  return legacy.map((item, i) => {
    if (isQuadrantConfig(item)) {
      const description = item.description;
      return {
        id: item.id,
        name: item.name,
        ...(description !== undefined ? { description } : {}),
        order: typeof item.order === 'number' ? item.order : i,
      };
    }
    // Fall-through: treat as a string name
    const name = typeof item === 'string' ? item : String(item);
    return {
      id: idGenerator(name, i),
      name,
      order: i,
    };
  });
}

/**
 * Shape of a proposed quadrant from an ID-first update payload.
 *
 * - `id` present → update/preserve an existing quadrant on the radar.
 * - `id` absent  → mint a new quadrant with a generated id.
 *
 * This is the shape accepted by AI tool executors (`updateRadarSettings`) and
 * by `reconcileQuadrantConfigs` directly.
 */
export interface ProposedQuadrantConfig {
  id?: string;
  name: string;
  description?: string;
}

/**
 * Result of reconciling a proposed quadrant list against the radar's existing
 * configs. Every field is actionable by the caller:
 *
 * - `next`     — the new canonical list, in proposed order, with preserved or minted ids.
 * - `added`    — brand-new configs (no `id` on the proposed side).
 * - `removed`  — ids that existed but are absent from `proposed` (feed into orphan check).
 * - `renamed`  — preserved-id rows whose display name changed (useful for agent reports).
 * - `errors`   — validation failures; when non-empty, `next` is `[]` and callers must reject.
 */
export interface ReconcileQuadrantsResult {
  next: QuadrantConfig[];
  added: QuadrantConfig[];
  removed: string[];
  renamed: Array<{ id: string; oldName: string; newName: string }>;
  errors: string[];
}

/**
 * ID-first reconciliation of a proposed quadrant list against a radar's current
 * configs. This is the single shape-preserving merge used by every "update
 * quadrants" code path — AI tool executor, `SettingsDialog` save, and the
 * signal-approval radar-edit path.
 *
 * Behavior (strict, never guesses):
 *
 * 1. Each proposed item with `id` must match an existing quadrant. Match → preserve id,
 *    update name/description. Miss → error "Unknown quadrant id: <id>".
 * 2. Each proposed item without `id` is new → mint a fresh id via `idGenerator`.
 * 3. Existing quadrants absent from `proposed` (compared by id) are removed and
 *    their ids listed in `removed` — the caller decides whether to run an orphan
 *    check before committing.
 * 4. Validation errors: empty proposed list, empty name, duplicate ids. Range is
 *    NOT checked here (MIN/MAX_QUADRANTS enforced by the service layer).
 *
 * When `errors` is non-empty the other fields are empty — callers should reject
 * the input and return the error list to the user/agent.
 */
export function reconcileQuadrantConfigs(
  existing: readonly QuadrantConfig[],
  proposed: readonly ProposedQuadrantConfig[],
  idGenerator: (name: string, index: number) => string
): ReconcileQuadrantsResult {
  const errors: string[] = [];

  if (proposed.length === 0) {
    errors.push('At least 1 quadrant is required');
    return { next: [], added: [], removed: [], renamed: [], errors };
  }

  // Build existing id → config lookup
  const existingById = new Map<string, QuadrantConfig>();
  for (const q of existing) {
    existingById.set(q.id, q);
  }

  // First pass: validate shapes and duplicate-id detection
  const seenIds = new Set<string>();
  const seenNames = new Set<string>();
  for (let i = 0; i < proposed.length; i++) {
    const item = proposed[i];
    const trimmedName = (item.name ?? '').trim();
    if (!trimmedName) {
      errors.push(`Quadrant at index ${i} has an empty name`);
      continue;
    }
    const lowerName = trimmedName.toLowerCase();
    if (seenNames.has(lowerName)) {
      errors.push(`Duplicate quadrant name: "${trimmedName}"`);
      continue;
    }
    seenNames.add(lowerName);
    if (item.id) {
      if (seenIds.has(item.id)) {
        errors.push(`Duplicate quadrant id: ${item.id}`);
        continue;
      }
      seenIds.add(item.id);
      if (!existingById.has(item.id)) {
        errors.push(
          `Unknown quadrant id: ${item.id}. Retry with an id from the current radar, or omit id to create a new quadrant.`
        );
      }
    }
  }

  if (errors.length > 0) {
    return { next: [], added: [], removed: [], renamed: [], errors };
  }

  // Second pass: build the next list
  const next: QuadrantConfig[] = [];
  const added: QuadrantConfig[] = [];
  const renamed: Array<{ id: string; oldName: string; newName: string }> = [];
  const keptIds = new Set<string>();

  for (let i = 0; i < proposed.length; i++) {
    const item = proposed[i];
    const trimmedName = item.name.trim();

    if (item.id) {
      // Validated above — safe to assert existingItem is present
      const existingItem = existingById.get(item.id)!;
      const description = item.description ?? existingItem.description;
      const updated: QuadrantConfig = {
        id: existingItem.id,
        name: trimmedName,
        ...(description !== undefined ? { description } : {}),
        order: i,
      };
      next.push(updated);
      keptIds.add(item.id);
      if (existingItem.name !== trimmedName) {
        renamed.push({ id: item.id, oldName: existingItem.name, newName: trimmedName });
      }
    } else {
      const minted: QuadrantConfig = {
        id: idGenerator(trimmedName, i),
        name: trimmedName,
        ...(item.description !== undefined ? { description: item.description } : {}),
        order: i,
      };
      next.push(minted);
      added.push(minted);
    }
  }

  // Third pass: compute removed ids
  const removed: string[] = [];
  for (const q of existing) {
    if (!keptIds.has(q.id)) {
      removed.push(q.id);
    }
  }

  return { next, added, removed, renamed, errors: [] };
}
